import { expect, test } from '@playwright/test';
import { createE2EState } from '../helpers/e2e-state.js';

function serializeState(state) {
  return JSON.stringify(state);
}

function localDateStr(date = new Date()) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

async function seedLegacyState(page, state) {
  await page.addInitScript((serializedState) => {
    window.Chart = class {
      destroy() {}
    };

    localStorage.clear();
    sessionStorage.clear();
    localStorage.setItem('estudo_state', serializedState);
  }, serializeState(state));
}

test.describe('Calendario', () => {
  test('creates a study event from a calendar date', async ({ page }) => {
    const state = createE2EState();
    const title = 'Evento criado pelo calendario';

    await seedLegacyState(page, state);
    await page.goto('/');
    await page.click('[data-view="calendar"]');

    const dateTarget = page.locator('[data-action="open-event-modal-date"]').first();
    await expect(dateTarget).toBeVisible();
    const date = await dateTarget.getAttribute('data-date');
    await dateTarget.click({ force: true });

    const modal = page.locator('#modal-event');
    await expect(modal).toHaveClass(/open/);
    await expect(page.locator('#event-data')).toHaveValue(date);

    await page.selectOption('#event-disc', 'disc_1');
    await page.fill('#event-titulo', title);
    await page.selectOption('#event-duracao', '60');
    await page.click('[data-action="save-event"]');

    await expect(modal).not.toHaveClass(/open/);
    await expect(page.locator('#main-content')).toContainText(title);
    await expect.poll(() => page.evaluate((eventTitle) => {
      return window.state.eventos.some(evento => evento.titulo === eventTitle);
    }, title)).toBe(true);
  });

  test('opens and deletes an existing calendar event from the detail modal', async ({ page }) => {
    const state = createE2EState();
    state.eventos.push({
      id: 'ev_calendar_delete',
      titulo: 'Evento para apagar no calendario',
      data: '2026-05-06',
      status: 'agendado',
      tempoAcumulado: 0,
      duracao: 60,
      tipo: 'conteudo',
      discId: 'disc_1',
    });

    await seedLegacyState(page, state);
    await page.goto('/');
    await page.click('[data-view="calendar"]');

    const chip = page.locator('[data-action="open-event-detail"][data-event-id="ev_calendar_delete"]');
    await expect(chip).toBeVisible();
    await chip.click();

    const detailModal = page.locator('#modal-event-detail');
    await expect(detailModal).toHaveClass(/open/);
    await expect(page.locator('#modal-event-detail-title')).toHaveText('Evento para apagar no calendario');

    await page.click('[data-action="delete-event-from-modal"][data-event-id="ev_calendar_delete"]');
    await expect(page.locator('#modal-confirm')).toHaveClass(/open/);
    await page.click('#confirm-ok-btn');

    await expect(detailModal).not.toHaveClass(/open/);
    await expect(chip).not.toBeVisible();
    await expect.poll(() => page.evaluate(() => {
      return window.state.eventos.some((evento) => evento.id === 'ev_calendar_delete');
    })).toBe(false);
  });

  test('deleting an auto-generated cycle event keeps future predictions for the discipline', async ({ page }) => {
    const state = createE2EState();
    state.planejamento = {
      ativo: true,
      tipo: 'ciclo',
      disciplinas: ['disc_1'],
      sequencia: [
        { id: 'seq_1', discId: 'disc_1', minutosAlvo: 60, concluido: false, status: 'pendente' },
      ],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-05-25T00:00:00.000Z',
      horarios: {
        diasAtivos: [0, 1, 2, 3, 4, 5, 6],
        dataInicial: '2026-05-26',
        dataFinal: '2026-05-27',
      },
      skippedSlots: [],
    };
    state.eventos.push({
      id: 'auto_2026-05-26_0_keep_prediction',
      titulo: 'Estudar Direito Constitucional',
      data: '2026-05-26',
      status: 'agendado',
      tempoAcumulado: 0,
      duracao: 60,
      tipo: 'conteudo',
      discId: 'disc_1',
      seqId: 'seq_1',
      slotIndex: 0,
      isAutoGenerated: true,
    });

    await seedLegacyState(page, state);
    await page.goto('/');
    await page.click('[data-view="calendar"]');

    const chip = page.locator(
      '[data-action="open-event-detail"][data-event-id="auto_2026-05-26_0_keep_prediction"]'
    );
    await expect(chip).toBeVisible();
    await chip.click();

    await page.click(
      '[data-action="delete-event-from-modal"][data-event-id="auto_2026-05-26_0_keep_prediction"]'
    );
    await expect(page.locator('#modal-confirm')).toHaveClass(/open/);
    await page.click('#confirm-ok-btn');

    await expect(chip).not.toBeVisible();
    await expect
      .poll(() =>
        page.evaluate(() => ({
          removed: !window.state.eventos.some(
            (evento) => evento.id === 'auto_2026-05-26_0_keep_prediction'
          ),
          status: window.state.planejamento.sequencia[0]?.status,
          skipped: window.state.planejamento.skippedSlots?.length,
        }))
      )
      .toEqual({ removed: true, status: 'pendente', skipped: 1 });

    await page.click('[data-view="ciclo"]');
    await expect(page.locator('#topbar-title')).toHaveText('Ciclo de Estudos', { timeout: 10000 });
    await expect(page.locator('.ciclo-predict-summary')).toContainText('5 sessões previstas');
    await expect(page.locator('#predict-results-container')).toContainText('Direito Constitucional');
    await expect(page.locator('#predict-results-container')).toContainText('5 sessões');
  });
  test('day load hint ignores scheduled events hidden by the active edital filter', async ({ page }) => {
    const state = createE2EState();
    const today = localDateStr();
    state.editais.push({
      id: 'ed_2',
      nome: 'Concurso TRT',
      cor: '#7c3aed',
      disciplinas: [
        {
          id: 'disc_2',
          nome: 'Direito do Trabalho',
          icone: '📘',
          cor: '#7c3aed',
          assuntos: [],
          aulas: [],
        },
      ],
    });
    state.eventos.push(
      {
        id: 'ev_visible_delete',
        titulo: 'Evento visivel para apagar',
        data: today,
        status: 'agendado',
        tempoAcumulado: 0,
        duracao: 60,
        tipo: 'conteudo',
        discId: 'disc_1',
      },
      {
        id: 'ev_hidden_1',
        titulo: 'Evento escondido 1',
        data: today,
        status: 'agendado',
        tempoAcumulado: 0,
        duracao: 120,
        tipo: 'conteudo',
        discId: 'disc_2',
      },
      {
        id: 'ev_hidden_2',
        titulo: 'Evento escondido 2',
        data: today,
        status: 'agendado',
        tempoAcumulado: 0,
        duracao: 120,
        tipo: 'conteudo',
        discId: 'disc_2',
      }
    );

    await seedLegacyState(page, state);
    await page.goto('/');
    await page.click('[data-view="calendar"]');

    const visibleChip = page.locator(
      '.cal-event-chip[data-action="open-event-detail"][data-event-id="ev_visible_delete"]'
    );
    await expect(visibleChip).toBeVisible();
    await expect(page.locator('#main-content')).not.toContainText('Evento escondido 1');

    await visibleChip.click();
    await page.click('[data-action="delete-event-from-modal"][data-event-id="ev_visible_delete"]');
    await expect(page.locator('#modal-confirm')).toHaveClass(/open/);
    await page.click('#confirm-ok-btn');

    await expect(visibleChip).not.toBeVisible();
    await expect
      .poll(() =>
        page.evaluate(() => window.state.eventos.some((event) => event.id === 'ev_visible_delete'))
      )
      .toBe(false);

    await page.click('[data-action="open-add-event"]');
    await expect(page.locator('#day-load-hint')).toContainText('Dia livre');
  });
});
