import { expect, test } from '@playwright/test';
import { createE2EState } from '../helpers/e2e-state.js';

// Valida o contrato de merge entre dispositivos usando o app real no browser:
// o dispositivo A exclui uma sessão manual e pula uma etapa do ciclo (excluindo
// a sessão auto-gerada); o payload exportado de A é mesclado no dispositivo B
// (mergeStudyStates — o mesmo caminho dos pulls Cloudflare/Drive/Firestore).
// A exclusão e o slot perdido devem propagar para B, e o round-trip de volta
// para A não pode ressuscitar nada.

function serializeState(state) {
  return JSON.stringify(state);
}

function localDateStr(date = new Date()) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

async function seedLegacyState(page, state) {
  await page.addInitScript((serializedState) => {
    window.Chart = class {
      destroy() {}
    };
    localStorage.clear();
    sessionStorage.clear();
    localStorage.setItem('estudo_state', serializedState);
  }, serializeState(state));
}

function createDeviceBaseline() {
  const state = createE2EState();
  const today = new Date();
  const todayStr = localDateStr(today);
  const tomorrowStr = localDateStr(new Date(today.getTime() + 24 * 60 * 60 * 1000));

  state.planejamento = {
    ativo: true,
    tipo: 'ciclo',
    disciplinas: ['disc_1'],
    relevancia: {},
    horarios: {
      diasAtivos: [0, 1, 2, 3, 4, 5, 6],
      dataInicial: todayStr,
      dataFinal: tomorrowStr,
    },
    sequencia: [
      { id: 'seq_1', discId: 'disc_1', minutosAlvo: 60, concluido: false, status: 'pendente' },
    ],
    skippedSlots: [],
    ciclosCompletos: 0,
    dataInicioCicloAtual: today.toISOString(),
  };
  state.eventos.push(
    {
      id: 'auto_seed_1',
      titulo: 'Estudar Direito Constitucional',
      data: todayStr,
      status: 'agendado',
      tempoAcumulado: 0,
      duracao: 60,
      tipo: 'conteudo',
      discId: 'disc_1',
      seqId: 'seq_1',
      slotIndex: 0,
      isAutoGenerated: true,
    },
    {
      id: 'ev_manual',
      titulo: 'Sessao manual para excluir',
      data: todayStr,
      status: 'agendado',
      tempoAcumulado: 0,
      tipo: 'conteudo',
      discId: 'disc_1',
      assId: null,
    }
  );
  return state;
}

async function deleteEventoViaCalendario(page, eventId) {
  const chip = page.locator(
    `.cal-event-chip[data-action="open-event-detail"][data-event-id="${eventId}"]`
  );
  await expect(chip).toBeVisible();
  await chip.click();
  await page.click(`[data-action="delete-event-from-modal"][data-event-id="${eventId}"]`);
  await expect(page.locator('#modal-confirm')).toHaveClass(/open/);
  await page.click('#confirm-ok-btn');
  await expect(chip).not.toBeVisible();
}

test.describe('Sync entre dispositivos (merge)', () => {
  test('exclusão e slot perdido no dispositivo A propagam para o B sem ressuscitar nada', async ({
    browser,
  }) => {
    // ---------- Dispositivo A ----------
    const ctxA = await browser.newContext();
    const pageA = await ctxA.newPage();
    await seedLegacyState(pageA, createDeviceBaseline());
    await pageA.goto('/');
    await pageA.click('[data-view="calendar"]');

    await deleteEventoViaCalendario(pageA, 'ev_manual');
    await deleteEventoViaCalendario(pageA, 'auto_seed_1');

    const estadoA = await pageA.evaluate(() => ({
      tombstones: (window.state.syncTombstones || []).map((t) => `${t.col}:${t.id}`),
      seqStatus: window.state.planejamento.sequencia[0]?.status,
      lost: window.state.planejamento.slotOverrides?.[0]?.status,
      planUpdatedAt: window.state.planejamento.updatedAt,
    }));
    expect(estadoA.tombstones).toContain('eventos:ev_manual');
    // Auto pendente sem tempo não gera tombstone: a perda fica registrada no slot.
    expect(estadoA.tombstones).not.toContain('eventos:auto_seed_1');
    expect(estadoA.seqStatus).toBe('pendente');
    expect(estadoA.lost).toBe('perdido');
    expect(estadoA.planUpdatedAt).toBeTruthy();

    const payloadA = await pageA.evaluate(async () => {
      const { createExportableState } = await import('/js/store.js?v=8.37');
      return createExportableState(window.state);
    });

    // ---------- Dispositivo B (ainda com o estado antigo) ----------
    const ctxB = await browser.newContext();
    const pageB = await ctxB.newPage();
    await seedLegacyState(pageB, createDeviceBaseline());
    await pageB.goto('/');
    await expect
      .poll(() => pageB.evaluate(() => window.state.eventos.some((e) => e.id === 'ev_manual')))
      .toBe(true);

    const estadoB = await pageB.evaluate(async (remote) => {
      const { mergeStudyStates } = await import('/js/sync/sync-center.js?v=8.37');
      const { setState } = await import('/js/store.js?v=8.37');
      const { syncCicloToEventos } = await import('/js/logic.js?v=8.37');
      // mesmo caminho do pull automático: merge remoto→local + regen do ciclo
      setState(mergeStudyStates(window.state, remote));
      syncCicloToEventos();
      return {
        eventIds: window.state.eventos.map((e) => e.id),
        seqStatus: window.state.planejamento.sequencia[0]?.status,
        lost: window.state.planejamento.slotOverrides?.[0]?.status,
        tombstones: (window.state.syncTombstones || []).map((t) => `${t.col}:${t.id}`),
      };
    }, payloadA);

    // A exclusão propagou e a perda do slot chegou no plano de B.
    expect(estadoB.eventIds).not.toContain('ev_manual');
    expect(estadoB.seqStatus).toBe('pendente');
    expect(estadoB.lost).toBe('perdido');
    expect(estadoB.tombstones).toContain('eventos:ev_manual');
    // O regen não recria o slot perdido.
    expect(estadoB.eventIds).not.toContain('auto_seed_1');

    // A UI de B não exibe o badge legado de etapa pulada.
    await pageB.click('[data-view="ciclo"]');
    await expect(pageB.locator('#topbar-title')).toHaveText('Ciclo de Estudos', {
      timeout: 10000,
    });
    await expect(pageB.locator('.seq-item-pulada-badge')).toHaveCount(0);

    // ---------- Round-trip B → A: nada ressuscita ----------
    const payloadB = await pageB.evaluate(async () => {
      const { createExportableState } = await import('/js/store.js?v=8.37');
      return createExportableState(window.state);
    });

    const estadoAFinal = await pageA.evaluate(async (remote) => {
      const { mergeStudyStates } = await import('/js/sync/sync-center.js?v=8.37');
      const { setState } = await import('/js/store.js?v=8.37');
      const { syncCicloToEventos } = await import('/js/logic.js?v=8.37');
      setState(mergeStudyStates(window.state, remote));
      syncCicloToEventos();
      return {
        eventIds: window.state.eventos.map((e) => e.id),
        seqStatus: window.state.planejamento.sequencia[0]?.status,
        lost: window.state.planejamento.slotOverrides?.[0]?.status,
      };
    }, payloadB);

    expect(estadoAFinal.eventIds).not.toContain('ev_manual');
    expect(estadoAFinal.eventIds).not.toContain('auto_seed_1');
    expect(estadoAFinal.seqStatus).toBe('pendente');
    expect(estadoAFinal.lost).toBe('perdido');

    await ctxA.close();
    await ctxB.close();
  });
});
