import { scheduleSave, state } from './store.js?v=8.37';
import { openRegistroSessao } from './registro-sessao.js?v=8.37';

// TIMER ENGINE (extracted to ./logic/timer.js)
export {
  timerIntervals,
  _pomodoroMode,
  _pomodoroAlarm,
  isTimerActive,
  getActiveTimerEventIds,
  getElapsedSeconds,
  toggleTimerMode,
  setCronoLivreGoal,
  setCronoLivreDisc,
  setCronoLivreAss,
  reattachTimers,
  startTimerForEvent,
  addTimerMinutes,
  toggleTimer,
  discardTimer,
} from './logic/timer.js';

// Internal imports for functions staying in logic.js that reference timer state
import { timerIntervals } from './logic/timer.js';

// REVISIONS & SPACED REPETITION (extracted to ./logic/revisions.js)
export {
  _revDateCache,
  invalidateRevCache,
  calcRevisionDates,
  _pendingRevCache,
  invalidatePendingRevCache,
  getPendingRevisoes,
} from './logic/revisions.js';

import { invalidatePendingRevCache } from './logic/revisions.js';

// AUTO-CICLO CLEANUP (extracted to ./logic/cycle.js)
export {
  previewClearAutoCicloEvents,
  clearAutoCicloEvents,
} from './logic/cycle.js';

// DISCIPLINE UTILS (extracted to ./logic/disc.js)
export {
  _discCache,
  _discIndex,
  invalidateDiscCache,
  getAllDisciplinas,
  getDisc,
} from './logic/disc.js';

import { invalidateDiscCache } from './logic/disc.js';
import { skipPlanejamentoEventBeforeDelete, syncCicloToEventos } from './logic/cycle.js';
import { recordSyncTombstone } from './sync/sync-center.js?v=8.37';

// PROGRESS & DASHBOARD ANALYTICS (extracted to ./logic/progress.js)
export {
  totalStudySeconds,
  calculateContentProgress,
  invalidateDashCaches,
  getAggregatedStats,
  getPerformanceStats,
  getPagesReadStats,
  getSyllabusProgress,
  invalidateStreakCache,
  getConsistencyStreak,
  getSubjectStats,
  getCurrentWeekStats,
  getAulasWeeklyStats,
  getPreviousWeekStats,
  getDisciplineSparkline,
  getNextSuggestedLesson,
  getDisciplineProgressByEdital,
  getSyllabusProgressByEdital,
  getPredictiveStats,
} from './logic/progress.js';

// Internal import for functions staying in logic.js that reference progress
import { invalidateDashCaches } from './logic/progress.js';

// PLANEJAMENTO DE ESTUDOS (extracted to ./logic/cycle.js)
export {
  calculateRelevanceWeights,
  generatePlanejamento,
  deletePlanejamento,
  resetCicloAndWipeEvents,
  calculateCyclePredictionsModel,
  getStudiedMinutesByDiscipline,
  distributeStudiedAcrossSeq,
  getCycleProgress,
  reconcileCycleProgress,
  getPlanejamentoSlotOverrides,
  getPlanejamentoMateriasPorDia,
  iniciarEtapaPlanejamento,
  syncCicloToEventos,
  substitutePlanejamentoSlot,
  moveCicloSeq,
  desfazerEtapa,
  marcarEtapaConcluida,
  editCicloSeqHours,
  touchPlanejamento,
} from './logic/cycle.js';

export function marcarEstudei(eventId) {
  openRegistroSessao(eventId);
}

// _marcarEstudeiDirect removida: sem callers em produção (o fluxo real passa
// pelo modal de registro → session-save.js) e disparava refreshMEDSections
// fora da view MED, o que sobrescreveria o main-content com a tela MED.

export function removeEvento(eventId) {
  const ev = state.eventos.find((e) => e.id === eventId);
  if (timerIntervals[eventId]) {
    clearInterval(timerIntervals[eventId]);
    delete timerIntervals[eventId];
  }
  const skippedPlanejamentoSlot = skipPlanejamentoEventBeforeDelete(ev);
  // Tombstone para o merge de sync não ressuscitar a exclusão. Autos pendentes
  // sem tempo ficam de fora: são derivados do plano (regenerados, id por device).
  const isDerivedAuto =
    !!ev?.isAutoGenerated && ev.status !== 'estudei' && !(Number(ev.tempoAcumulado) > 0);
  if (ev && !isDerivedAuto) recordSyncTombstone(state, 'eventos', eventId);
  state.eventos = state.eventos.filter((e) => e.id !== eventId);
  if (skippedPlanejamentoSlot) {
    syncCicloToEventos();
  }
  scheduleSave();
  invalidatePendingRevCache();
  document.dispatchEvent(new CustomEvent('app:eventoDeleted', { detail: { eventId } }));
}

export function deleteEvento(eventId) {
  document.dispatchEvent(
    new CustomEvent('app:showConfirm', {
      detail: {
        msg: 'Excluir este evento permanentemente?',
        onYes: () => {
          removeEvento(eventId);
        },
        opts: { danger: true, label: 'Excluir', title: 'Excluir evento' },
      },
    })
  );
}

// =============================================
// DISCIPLINE UTILS
// =============================================

export function archiveDiscipline(editalId, disciplineId) {
  const edital = state.editais.find((e) => e.id === editalId);
  if (!edital) return;
  const disc = edital.disciplinas?.find((d) => d.id === disciplineId);
  if (!disc) return;
  disc.arquivada = true;
  disc.arquivadaEm = new Date().toISOString();
  invalidateDiscCache();
  invalidateDashCaches();
  invalidatePendingRevCache();
  scheduleSave();
}

export function unarchiveDiscipline(editalId, disciplineId) {
  const edital = state.editais.find((e) => e.id === editalId);
  if (!edital) return;
  const disc = edital.disciplinas?.find((d) => d.id === disciplineId);
  if (!disc) return;
  disc.arquivada = false;
  disc.arquivadaEm = null;
  invalidateDiscCache();
  invalidateDashCaches();
  invalidatePendingRevCache();
  scheduleSave();
}

export function getActiveDisciplinas() {
  const result = [];
  for (const edital of state.editais) {
    if (edital.arquivado) continue;
    if (!edital.disciplinas) continue;
    for (const disc of edital.disciplinas) {
      if (disc.arquivada) continue;
      result.push({ disc, edital });
    }
  }
  return result;
}

// =============================================
// EDITAL ARCHIVE / SINGLE-PRINCIPAL UTILS
// =============================================
// Modelo de "edital principal único": exatamente um edital fica ativo
// (arquivado=false) e é o principal; os demais ficam arquivados, com TODOS os
// dados preservados (disciplinas, assuntos, sessões em state.eventos). Espelha o
// arquivamento de disciplina (disc.arquivada). Nunca chamar deleteEdital aqui —
// arquivar não apaga nada e, por isso, não precisa de tombstone de sync.

export function getActiveEditais() {
  return (state.editais || []).filter((e) => !e.arquivado);
}

export function getArchivedEditais() {
  return (state.editais || []).filter((e) => e.arquivado);
}

/**
 * Edital principal = o (primeiro) edital ativo. Função PURA — não muta.
 * Casos de borda pós-merge de sync: 0 ativos → null; >1 ativos → o primeiro por
 * ordem do array (estável; a reconciliação no init resolve para exatamente um).
 */
export function getPrincipalEdital() {
  return getActiveEditais()[0] || null;
}

export function getPrincipalEditalId() {
  return getPrincipalEdital()?.id || null;
}

export function archiveEdital(editalId) {
  const edital = (state.editais || []).find((e) => e.id === editalId);
  if (!edital) return;
  edital.arquivado = true;
  edital.arquivadoEm = new Date().toISOString();
  invalidateDiscCache();
  invalidateDashCaches();
  invalidatePendingRevCache();
  scheduleSave();
}

export function unarchiveEdital(editalId) {
  const edital = (state.editais || []).find((e) => e.id === editalId);
  if (!edital) return;
  edital.arquivado = false;
  edital.arquivadoEm = null;
  invalidateDiscCache();
  invalidateDashCaches();
  invalidatePendingRevCache();
  scheduleSave();
}

/**
 * Promove um edital a principal de forma ATÔMICA: o alvo vira ativo e todos os
 * outros editais ativos são arquivados. Garante o invariante "exatamente um
 * principal". No-op se o id não existir (preserva o principal atual).
 */
export function makeEditalPrincipal(editalId) {
  const target = (state.editais || []).find((e) => e.id === editalId);
  if (!target) return;
  const now = new Date().toISOString();
  for (const edital of state.editais) {
    if (edital.id === editalId) {
      edital.arquivado = false;
      edital.arquivadoEm = null;
    } else if (!edital.arquivado) {
      edital.arquivado = true;
      edital.arquivadoEm = now;
    }
  }
  invalidateDiscCache();
  invalidateDashCaches();
  invalidatePendingRevCache();
  scheduleSave();
}
