import { scheduleSave, state } from '../store.js?v=8.37';
import { todayStr, getLocalDateStr, uid, esc } from '../utils.js?v=8.37';
import { navigate, closeModal, openModal } from '../app.js?v=8.37';
import { timerIntervals, toggleTimer } from './timer.js';
import { getDisc } from './disc.js';
import { invalidatePendingRevCache } from './revisions.js';

// =============================================
// AUTO-CICLO CLEANUP
// =============================================

/**
 * Categoriza eventos do calendário pelo critério de "limpeza do Ciclo".
 * Não muta nada — só inspeciona e conta.
 *
 * Um evento entra em `toDelete` se TODAS forem verdade:
 *  - foi auto-gerado pelo Ciclo (`isAutoGenerated === true`)
 *  - ainda não foi concluído (`status !== 'estudei'`)
 *  - não tem tempo registrado (`tempoAcumulado || 0 === 0`)
 *  - é hoje ou futuro (`data >= todayStr()`)
 *
 * Os demais ficam preservados, particionados nas categorias:
 *  - manual: criado pelo usuário (sem flag `isAutoGenerated`)
 *  - withProgress: tem tempo registrado (qualquer status)
 *  - concluded: status === 'estudei'
 *  - past: ficou no passado (data < hoje) e não tem outra categoria
 */
export function previewClearAutoCicloEvents(reference = state.eventos) {
  const today = todayStr();
  const result = {
    toDelete: [],
    preservedManual: [],
    preservedWithProgress: [],
    preservedConcluded: [],
    preservedPast: [],
  };
  for (const ev of reference || []) {
    if (!ev || typeof ev !== 'object') continue;
    if (ev.status === 'estudei') {
      result.preservedConcluded.push(ev);
      continue;
    }
    if ((Number(ev.tempoAcumulado) || 0) > 0) {
      result.preservedWithProgress.push(ev);
      continue;
    }
    if (!ev.isAutoGenerated) {
      result.preservedManual.push(ev);
      continue;
    }
    const evDate = String(ev.data || '');
    if (evDate && evDate < today) {
      result.preservedPast.push(ev);
      continue;
    }
    result.toDelete.push(ev);
  }
  return result;
}

/**
 * Aplica `previewClearAutoCicloEvents` ao estado, removendo os eventos
 * marcados como `toDelete` e persistindo via scheduleSave. Retorna o resumo
 * (com counts) — útil para a camada de UI mostrar feedback.
 */
export function clearAutoCicloEvents() {
  const preview = previewClearAutoCicloEvents();
  if (preview.toDelete.length === 0) {
    return {
      deleted: 0,
      preservedManual: preview.preservedManual.length,
      preservedWithProgress: preview.preservedWithProgress.length,
      preservedConcluded: preview.preservedConcluded.length,
      preservedPast: preview.preservedPast.length,
    };
  }
  const toDeleteIds = new Set(preview.toDelete.map((ev) => ev.id));
  // Limpa intervalos de timer de eventos a remover (defensivo — eventos sem
  // tempoAcumulado normalmente não têm timer, mas pode haver corrida)
  for (const id of toDeleteIds) {
    if (timerIntervals[id]) {
      clearInterval(timerIntervals[id]);
      delete timerIntervals[id];
    }
  }
  state.eventos = (state.eventos || []).filter((ev) => !toDeleteIds.has(ev.id));
  scheduleSave();
  invalidatePendingRevCache();
  document.dispatchEvent(
    new CustomEvent('app:eventosBulkDeleted', {
      detail: { ids: [...toDeleteIds], reason: 'clear-auto-ciclo' },
    })
  );
  return {
    deleted: toDeleteIds.size,
    preservedManual: preview.preservedManual.length,
    preservedWithProgress: preview.preservedWithProgress.length,
    preservedConcluded: preview.preservedConcluded.length,
    preservedPast: preview.preservedPast.length,
  };
}

// =============================================
// PLANEJAMENTO DE ESTUDOS (WIZARD)
// =============================================

export function calculateRelevanceWeights(relevanciaDraft) {
  let totalPeso = 0;
  const result = {};

  for (const discId in relevanciaDraft) {
    const r = relevanciaDraft[discId];
    const imp = parseInt(r.importancia, 10) || 3;
    const con = parseInt(r.conhecimento, 10) || 3;

    // Conhecimento 0 -> Fato 6 (muita atenção)
    // Conhecimento 5 -> Fato 1 (pouca atenção)
    const fatorConhecimento = 6 - con;
    const peso = imp * fatorConhecimento;

    result[discId] = { importancia: imp, conhecimento: con, peso };
    totalPeso += peso;
  }

  for (const discId in result) {
    result[discId].percentual = totalPeso > 0 ? (result[discId].peso / totalPeso) * 100 : 0;
  }

  return result;
}

export function generatePlanejamento(draft) {
  const plan = {
    ativo: true,
    tipo: draft.tipo,
    disciplinas: draft.disciplinas,
    relevancia: calculateRelevanceWeights(draft.relevancia),
    horarios: draft.horarios,
    sequencia: [],
    skippedSlots: [],
    ciclosCompletos: 0,
    dataInicioCicloAtual: new Date().toISOString(),
  };

  let totalMinutes = 0;

  if (plan.tipo === 'ciclo') {
    const horasSemanais = parseFloat(plan.horarios.horasSemanais) || 0;
    totalMinutes = horasSemanais * 60;
  } else if (plan.tipo === 'semanal') {
    for (let i = 0; i < 7; i++) {
      const hora = plan.horarios.horasPorDia[i];
      if (plan.horarios.diasAtivos.includes(i) && hora && hora.includes(':')) {
        const [hh, mm] = hora.split(':');
        totalMinutes += parseInt(hh, 10) * 60 + parseInt(mm, 10);
      }
    }
  }

  const minSessao = parseInt(plan.horarios.sessaoMin, 10) || 30;
  const maxSessao = parseInt(plan.horarios.sessaoMax, 10) || 120;

  const sortedDiscs = [...plan.disciplinas].sort((a, b) => {
    const wA = plan.relevancia[a]?.peso || 0;
    const wB = plan.relevancia[b]?.peso || 0;
    return wB - wA;
  });

  const pools = [];

  sortedDiscs.forEach((discId) => {
    const perc = plan.relevancia[discId]?.percentual || 0;
    let targetMinutes = Math.round((perc / 100) * totalMinutes);
    if (targetMinutes < minSessao && totalMinutes > 0) targetMinutes = minSessao;

    const discBlocks = [];
    let remaining = targetMinutes;
    while (remaining > 0 && totalMinutes > 0) {
      let block = Math.min(remaining, maxSessao);
      if (block < minSessao && remaining === targetMinutes) {
        block = minSessao;
      } else if (block < minSessao && remaining < targetMinutes) {
        break; // drop remaining tail
      }
      discBlocks.push({
        id: 'seq_' + uid(),
        discId: discId,
        minutosAlvo: block,
        concluido: false,
        status: 'pendente',
      });
      remaining -= block;
    }
    if (discBlocks.length > 0) pools.push(discBlocks);
  });

  // Interleave blocks (Round-Robin) to avoid studying the same subject consecutively
  let hasMore = true;
  while (hasMore) {
    hasMore = false;
    for (let i = 0; i < pools.length; i++) {
      if (pools[i].length > 0) {
        plan.sequencia.push(pools[i].shift());
        hasMore = true;
      }
    }
  }

  state.planejamento = plan;
  resetCicloAndWipeEvents(); // Use the deep wipe when generating completely anew
  return plan;
}

export function deletePlanejamento() {
  document.dispatchEvent(
    new CustomEvent('app:showConfirm', {
      detail: {
        msg: 'Deseja excluir este Planejamento de Estudos? Você precisará criar um novo depois para gerar sequências.',
        onYes: () => {
          state.planejamento = {
            ativo: false,
            tipo: null,
            disciplinas: [],
            relevancia: {},
            horarios: {},
            sequencia: [],
            skippedSlots: [],
          };
          resetCicloAndWipeEvents();
          document.dispatchEvent(new Event('app:renderCurrentView'));
        },
        opts: { title: 'Excluir Planejamento' },
      },
    })
  );
}

export function resetCicloAndWipeEvents() {
  if (!state.planejamento) return;
  state.planejamento.skippedSlots = [];

  // 1. Wipe all planned cycle events that are not studied yet (including past ones).
  state.eventos = state.eventos.filter((e) => {
    const isCyclePlannedEvent = e.isAutoGenerated || Boolean(e.seqId);
    if (!isCyclePlannedEvent) return true;
    if (e.status === 'estudei' || (e.tempoAcumulado && e.tempoAcumulado > 0)) return true;
    return false; // Remove pending auto generated events completely
  });

  // 2. Reset the sequence conclusion state
  if (state.planejamento.sequencia) {
    state.planejamento.sequencia.forEach((seq) => {
      seq.concluido = false;
      seq.status = 'pendente';
      delete seq.finalizadoEm;
      delete seq.puladaEm;
    });
  }

  // 3. Re-inject clean
  syncCicloToEventos();
  scheduleSave();
}

function getActiveStudyDaysFilter(plan = state.planejamento) {
  const diasAtivos = plan?.horarios?.diasAtivos;
  if (!Array.isArray(diasAtivos)) return null;

  const normalizedDays = diasAtivos
    .map((day) => Number(day))
    .filter((day) => Number.isInteger(day) && day >= 0 && day <= 6);

  // No ciclo, os dias são opcionais; lista vazia mantém o comportamento livre (todos os dias).
  if (plan?.tipo === 'ciclo' && normalizedDays.length === 0) return null;

  return new Set(normalizedDays);
}

function getSeqStatus(seq) {
  if (seq?.status) return seq.status;
  return seq?.concluido ? 'concluida' : 'pendente';
}

function isPlanejamentoSeqPending(seq) {
  return getSeqStatus(seq) === 'pendente';
}

function getPendingPlanejamentoSequence(plan = state.planejamento) {
  return (plan?.sequencia || []).filter((seq) => isPlanejamentoSeqPending(seq));
}

function getStudiedMinutesForSeq(seqId) {
  if (!seqId) return 0;
  return (state.eventos || [])
    .filter((event) => event?.seqId === seqId && event.status === 'estudei')
    .reduce((total, event) => total + Math.round((Number(event.tempoAcumulado) || 0) / 60), 0);
}

/**
 * Soma (em minutos) das sessões concluídas por disciplina, derivada de state.eventos.
 * Fonte única para "minutos estudados por disciplina" — qualquer view deve usar este helper
 * em vez de contadores incrementais persistidos, garantindo que editar/excluir uma sessão
 * reflita automaticamente em todos os lugares.
 * @param {{ since?: string, discId?: string }} [opts]
 *   since  = data mínima 'YYYY-MM-DD' (compara com ev.dataEstudo||ev.data); sem corte por padrão.
 *   discId = se passado, retorna apenas os minutos dessa disciplina (number) em vez do mapa.
 * @returns {Record<string, number> | number} mapa discId->minutos, ou número se discId for dado.
 */
export function getStudiedMinutesByDiscipline(opts = {}) {
  const { since, discId } = opts;
  const totals = {};
  for (const ev of state.eventos || []) {
    if (!ev || ev.status !== 'estudei') continue;
    const minutos = Math.round((Number(ev.tempoAcumulado) || 0) / 60);
    if (minutos <= 0) continue;
    if (since) {
      const evDate = ev.dataEstudo || ev.data;
      if (!evDate || evDate < since) continue;
    }
    if (discId && ev.discId !== discId) continue;
    if (!ev.discId) continue;
    totals[ev.discId] = (totals[ev.discId] || 0) + minutos;
  }
  return discId ? totals[discId] || 0 : totals;
}

function getRemainingMinutesForSeq(seq) {
  const target = Math.max(0, Math.round(Number(seq?.minutosAlvo) || 0));
  if (target <= 0) return 0;
  if (getSeqStatus(seq) === 'concluida') return 0;
  return Math.max(target - getStudiedMinutesForSeq(seq.id), 0);
}

function formatPlanningMinutes(minutes) {
  const total = Math.max(0, Math.round(Number(minutes) || 0));
  const hours = Math.floor(total / 60);
  const mins = total % 60;
  if (hours > 0) return mins > 0 ? `${hours}h ${mins}min` : `${hours}h`;
  return `${mins}min`;
}

function getSkippedSlotKey(data, slotIndex) {
  return `${data || ''}#${Number(slotIndex) || 0}`;
}

function getSkippedSlotKeySet(plan = state.planejamento) {
  return new Set(
    (plan?.skippedSlots || [])
      .filter((slot) => slot?.data)
      .map((slot) => getSkippedSlotKey(slot.data, slot.slotIndex))
  );
}

function inferSlotIndex(eventToDelete) {
  if (Number.isInteger(Number(eventToDelete?.slotIndex))) return Number(eventToDelete.slotIndex);
  const sameDay = (state.eventos || []).filter(
    (ev) => ev?.data === eventToDelete?.data && (ev.seqId || ev.isAutoGenerated)
  );
  return Math.max(
    0,
    sameDay.findIndex((ev) => ev.id === eventToDelete?.id)
  );
}

export function skipPlanejamentoEventBeforeDelete(eventToDelete) {
  if (!eventToDelete?.seqId || !state.planejamento?.sequencia) return false;
  if (eventToDelete.status === 'estudei' || (Number(eventToDelete.tempoAcumulado) || 0) > 0) {
    return false;
  }

  const seq = state.planejamento.sequencia.find((item) => item.id === eventToDelete.seqId);
  if (!seq || !isPlanejamentoSeqPending(seq)) return false;

  const slotIndex = inferSlotIndex(eventToDelete);
  const data = eventToDelete.data || todayStr();
  if (!Array.isArray(state.planejamento.skippedSlots)) {
    state.planejamento.skippedSlots = [];
  }

  const key = getSkippedSlotKey(data, slotIndex);
  const alreadySkipped = state.planejamento.skippedSlots.some(
    (slot) => getSkippedSlotKey(slot.data, slot.slotIndex) === key
  );
  if (!alreadySkipped) {
    state.planejamento.skippedSlots.push({
      data,
      slotIndex,
      seqId: eventToDelete.seqId,
      eventIdOriginal: eventToDelete.id,
      criadoEm: new Date().toISOString(),
    });
  }

  return true;
}

export function calculateCyclePredictionsModel(startDateStr, endDateStr) {
  if (
    !state.planejamento ||
    !state.planejamento.sequencia ||
    state.planejamento.sequencia.length === 0
  )
    return {};

  const start = new Date(startDateStr + 'T00:00:00');
  const end = new Date(endDateStr + 'T23:59:59');
  if (isNaN(start) || isNaN(end) || start > end) return {};

  const seq = getPendingPlanejamentoSequence();
  if (seq.length === 0) return {};
  const materiasPorDia = state.config.materiasPorDia || 3;
  const activeDaysFilter = getActiveStudyDaysFilter(state.planejamento);
  const skippedSlots = getSkippedSlotKeySet(state.planejamento);
  let simulatedIdx = 0;

  const projection = {};

  for (let d = new Date(start); d <= end; d.setDate(d.getDate() + 1)) {
    if (activeDaysFilter && !activeDaysFilter.has(d.getDay())) continue;
    const dateStr = getLocalDateStr(d);

    for (let m = 0; m < materiasPorDia; m++) {
      if (skippedSlots.has(getSkippedSlotKey(dateStr, m))) {
        simulatedIdx = (simulatedIdx + 1) % seq.length;
        continue;
      }
      const seqItem = seq[simulatedIdx];
      if (!seqItem) break;

      if (!projection[seqItem.discId]) {
        projection[seqItem.discId] = { sessoes: 0, minutos: 0 };
      }
      const remainingMinutes = getRemainingMinutesForSeq(seqItem);
      if (remainingMinutes <= 0) {
        simulatedIdx = (simulatedIdx + 1) % seq.length;
        continue;
      }
      projection[seqItem.discId].sessoes++;
      projection[seqItem.discId].minutos += remainingMinutes;

      simulatedIdx = (simulatedIdx + 1) % seq.length;
    }
  }

  return projection;
}

export function iniciarEtapaPlanejamento(seqId) {
  if (!state.planejamento || !state.planejamento.sequencia) return;
  const seq = state.planejamento.sequencia.find((s) => s.id === seqId);
  if (!seq) return;
  const targetMinutes = Math.max(0, Math.round(Number(seq.minutosAlvo) || 0));
  const studiedMinutes = getStudiedMinutesForSeq(seq.id);
  const remainingMinutes = getRemainingMinutesForSeq(seq) || targetMinutes;

  if (studiedMinutes > 0 && remainingMinutes > 0 && remainingMinutes < targetMinutes) {
    openPartialPlanningStartPrompt(seq, remainingMinutes, studiedMinutes, targetMinutes);
    return;
  }

  startPlanningSequenceEvent(seq, remainingMinutes);
}

function startPlanningSequenceEvent(seq, durationMinutes, extra = {}) {
  const d = getDisc(seq.discId);

  const evento = {
    id: 'ev_' + uid(),
    titulo: `Estudar ${d?.disc.nome || 'Disciplina'}`,
    data: todayStr(),
    duracao: durationMinutes,
    status: 'agendado',
    tempoAcumulado: 0,
    tipo: 'conteudo',
    discId: seq.discId,
    assId: null,
    habito: null,
    seqId: seq.id,
    criadoEm: new Date().toISOString(),
    ...extra,
  };

  state.eventos.push(evento);
  scheduleSave();

  // Start ticking BEFORE routing
  toggleTimer(evento.id);

  // Switch to Cronometro and let the component render the already active event
  navigate('cronometro');
}

function openPartialPlanningStartPrompt(seq, remainingMinutes, studiedMinutes, targetMinutes) {
  const titleEl = document.getElementById('modal-prompt-title');
  const bodyEl = document.getElementById('modal-prompt-body');
  const saveBtn = document.getElementById('modal-prompt-save');
  if (!titleEl || !bodyEl || !saveBtn) {
    startPlanningSequenceEvent(seq, remainingMinutes);
    return;
  }

  titleEl.textContent = 'Continuar etapa parcial';
  saveBtn.textContent = 'Retomar anterior';
  bodyEl.innerHTML = `
    <div class="modal-note">
      VocÃª jÃ¡ estudou ${esc(formatPlanningMinutes(studiedMinutes))} de ${esc(formatPlanningMinutes(targetMinutes))}.
      A prÃ³xima meta serÃ¡ de ${esc(formatPlanningMinutes(remainingMinutes))}.
    </div>
    <div class="flex gap-sm mt-3">
      <button type="button" class="btn btn-ghost" id="prompt-start-new-session">Criar nova sessÃ£o</button>
    </div>
  `;

  const start = (mode) => {
    closeModal('modal-prompt');
    saveBtn.textContent = 'Salvar';
    startPlanningSequenceEvent(seq, remainingMinutes, {
      partialMode: mode,
      minutosAlvoOriginal: targetMinutes,
      minutosJaEstudadosAoIniciar: studiedMinutes,
    });
  };

  saveBtn.onclick = () => start('retomar');
  document.getElementById('prompt-start-new-session').onclick = () => start('nova');

  openModal('modal-prompt');
}

export function syncCicloToEventos() {
  if (
    !state.planejamento ||
    !state.planejamento.ativo ||
    !state.planejamento.sequencia ||
    state.planejamento.sequencia.length === 0
  )
    return;

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // 1. Apagar eventos futuros automáticos
  state.eventos = state.eventos.filter((e) => {
    if (!e.isAutoGenerated) return true;
    if (e.status === 'estudei' || (e.tempoAcumulado && e.tempoAcumulado > 0)) return true;
    const evDate = new Date(e.data + 'T00:00:00');
    if (evDate < today) return true;
    return false;
  });

  const seq = getPendingPlanejamentoSequence();
  if (seq.length === 0) return;
  const materiasPorDia = state.config.materiasPorDia || 3;
  const activeDaysFilter = getActiveStudyDaysFilter(state.planejamento);
  const skippedSlots = getSkippedSlotKeySet(state.planejamento);
  let currentSeqIdx = 0;

  // Pega o índice a partir do primeiro bloco "não concluído", caso preexistente no ciclo contínuo
  const firstPendentIndex = seq.findIndex((s) => isPlanejamentoSeqPending(s));
  if (firstPendentIndex !== -1) currentSeqIdx = firstPendentIndex;

  const horarios = state.planejamento.horarios || {};
  const scheduleStart = new Date(today);
  if (horarios.dataInicial) {
    const initialDateObj = new Date(horarios.dataInicial + 'T00:00:00');
    if (!isNaN(initialDateObj) && initialDateObj > scheduleStart) {
      scheduleStart.setTime(initialDateObj.getTime());
    }
  }

  // Determina quantos dias vamos agendar no futuro
  let maxDiasOffset = 14; // Default caso não haja dataFinal configurada
  if (horarios.dataFinal) {
    const finalDateObj = new Date(horarios.dataFinal + 'T23:59:59');
    if (isNaN(finalDateObj) || finalDateObj < scheduleStart) return;
    // Diferença em dias
    const diffTime = Math.abs(finalDateObj - scheduleStart);
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    // Limitador de segurança máximo (ex: 365 dias)
    maxDiasOffset = Math.min(diffDays + 1, 365);
  }

  // Injeta eventos ao calendário usando o limite dinâmico
  for (let diasOffset = 0; diasOffset < maxDiasOffset; diasOffset++) {
    const d = new Date(scheduleStart);
    d.setDate(d.getDate() + diasOffset);
    if (activeDaysFilter && !activeDaysFilter.has(d.getDay())) continue;

    const dtStr = getLocalDateStr(d);

    for (let m = 0; m < materiasPorDia; m++) {
      if (skippedSlots.has(getSkippedSlotKey(dtStr, m))) {
        currentSeqIdx = (currentSeqIdx + 1) % seq.length;
        continue;
      }
      const seqItem = seq[currentSeqIdx];
      if (!seqItem) break; // guard: empty or exhausted sequence
      const remainingMinutes = getRemainingMinutesForSeq(seqItem);
      if (remainingMinutes <= 0) {
        currentSeqIdx = (currentSeqIdx + 1) % seq.length;
        continue;
      }
      const discEntry = getDisc(seqItem.discId);

      state.eventos.push({
        id: 'auto_' + dtStr + '_' + currentSeqIdx + '_' + uid(),
        titulo: `Estudar ${discEntry?.disc.nome || 'Disciplina'}`,
        data: dtStr,
        duracao: remainingMinutes,
        status: 'agendado',
        tempoAcumulado: 0,
        tipo: 'conteudo',
        discId: seqItem.discId,
        assId: null,
        habito: null,
        seqId: seqItem.id,
        slotIndex: m,
        criadoEm: new Date().toISOString(),
        isAutoGenerated: true,
      });

      currentSeqIdx = (currentSeqIdx + 1) % seq.length;
    }
  }
}

export function moveCicloSeq(idx, dir) {
  if (!state.planejamento || !state.planejamento.sequencia) return;
  const seq = state.planejamento.sequencia;
  if (idx + dir < 0 || idx + dir >= seq.length) return;
  const temp = seq[idx];
  seq[idx] = seq[idx + dir];
  seq[idx + dir] = temp;
  syncCicloToEventos();
  scheduleSave();
  document.dispatchEvent(new Event('app:renderCurrentView'));
}

export function desfazerEtapa(seqId) {
  if (!state.planejamento || !state.planejamento.sequencia) return;
  const idx = state.planejamento.sequencia.findIndex((s) => s.id === seqId);
  if (idx > -1) {
    state.planejamento.sequencia[idx].concluido = false;
    state.planejamento.sequencia[idx].status = 'pendente';
    delete state.planejamento.sequencia[idx].puladaEm;
    delete state.planejamento.sequencia[idx].finalizadoEm;
    syncCicloToEventos();
    scheduleSave();
    document.dispatchEvent(new Event('app:renderCurrentView'));
    closeModal('modal-ciclo-history');
  }
}

export function marcarEtapaConcluida(seqId) {
  if (!state.planejamento || !state.planejamento.sequencia) return;
  const seq = state.planejamento.sequencia.find((s) => s.id === seqId);
  if (!seq) return;
  seq.concluido = true;
  seq.status = 'concluida';
  seq.finalizadoEm = new Date().toISOString();
  delete seq.puladaEm;
  syncCicloToEventos();
  scheduleSave();
  document.dispatchEvent(new Event('app:renderCurrentView'));
}

export function editCicloSeqHours(idx) {
  if (!state.planejamento || !state.planejamento.sequencia) return;
  const seqItem = state.planejamento.sequencia[idx];
  const currentHours = (seqItem.minutosAlvo / 60).toFixed(1).replace('.0', '');

  const titleEl = document.getElementById('modal-prompt-title');
  const bodyEl = document.getElementById('modal-prompt-body');
  const saveBtn = document.getElementById('modal-prompt-save');
  if (!titleEl || !bodyEl || !saveBtn) return;

  titleEl.textContent = 'Editar Carga Horária';
  bodyEl.innerHTML = `
    <div style="margin-bottom:12px;color:var(--text-secondary);font-size:14px;">
      Digite a nova carga horária (em horas) para esta etapa.<br>
      <small>Ex: 1 = Uma hora | 1.5 = 1h30min</small>
    </div>
    <input type="number" id="prompt-input-horas" class="form-control" value="${esc(currentHours)}" min="0.1" step="0.5" autofocus>
  `;

  saveBtn.onclick = () => {
    const novaStr = document.getElementById('prompt-input-horas')?.value || '';
    const novaHoras = parseFloat(novaStr.replace(',', '.'));
    if (isNaN(novaHoras) || novaHoras <= 0) {
      document.dispatchEvent(
        new CustomEvent('app:showToast', {
          detail: { msg: 'Valor inválido. Digite um número maior que zero.', type: 'error' },
        })
      );
      return;
    }
    seqItem.minutosAlvo = Math.round(novaHoras * 60);
    syncCicloToEventos();
    scheduleSave();
    closeModal('modal-prompt');
    document.dispatchEvent(new Event('app:renderCurrentView'));
  };

  openModal('modal-prompt');
  setTimeout(() => document.getElementById('prompt-input-horas')?.focus(), 100);
}
