// =============================================
// RETA FINAL — ORQUESTRAÇÃO (estado + agendador)
// Camada com estado sobre o núcleo puro (reta-final-core.js): materializa os
// blocos do cronograma dia-a-dia como eventos do calendário (rfBlocoId,
// análogo ao seqId do Ciclo). Importada por logic/cycle.js (roteamento de
// syncCicloToEventos) — por isso este módulo só importa store/utils/core,
// nunca cycle.js (evita ciclo de imports).
// =============================================
import { scheduleSave, state } from '../store.js?v=8.37';
import { todayStr, uid } from '../utils.js?v=8.37';
import {
  applyTopicosToEvent,
  buildTopicosFromRetaFinalBloco,
} from '../registro-sessao/session-topics.js';
import {
  buildRetaFinalEventTitle,
  matchRetaFinalToEditais,
  normalizeNameKey,
  reconcileRetaFinalWithEvents,
  rolloverRetaFinalBlocks,
  validateRetaFinalPayload,
} from './reta-final-core.js';

function deepClone(value) {
  return JSON.parse(JSON.stringify(value));
}

function isRetaFinalPlan(plan = state.planejamento) {
  return Boolean(plan?.ativo && plan.tipo === 'reta_final' && plan.retaFinal);
}

/**
 * Blocos já consumidos por eventos preservados (sessão estudada ou com tempo
 * acumulado). O agendador não pode re-materializar nem rolar esses blocos —
 * análogo exato do occupiedSlots do Ciclo (bug histórico da "sessão que
 * volta", commit 8756f10).
 * @returns {Set<string>}
 */
export function getRetaFinalOccupiedBlocoIds(eventos = state.eventos) {
  const occupied = new Set();
  for (const ev of eventos || []) {
    if (!ev?.rfBlocoId) continue;
    if (ev.status === 'estudei' || Number(ev.tempoAcumulado) > 0) occupied.add(ev.rfBlocoId);
  }
  return occupied;
}

function isPreservedEvent(ev) {
  return ev.status === 'estudei' || Number(ev.tempoAcumulado) > 0;
}

/**
 * Agendador idempotente da Reta Final (chamado no boot, no render da view e
 * roteado por syncCicloToEventos quando tipo === 'reta_final'):
 *  1. reconcilia blocos com eventos (estudei → concluido);
 *  2. rola blocos atrasados para hoje (pós-dataFinal → nao_coberto);
 *  3. remove autos órfãos não preservados (bloco sumiu/rolou/concluiu);
 *  4. materializa eventos para blocos pendentes de hoje/futuro sem evento.
 * Nunca chama touchPlanejamento() — rolagem/reconcile são views derivadas dos
 * eventos, re-deriváveis em cada dispositivo (anti ping-pong LWW).
 */
export function syncRetaFinalToEventos() {
  if (!isRetaFinalPlan()) return;
  const plan = state.planejamento;
  const retaFinal = plan.retaFinal;
  const today = todayStr();

  const reconcile = reconcileRetaFinalWithEvents(plan, state.eventos);
  const occupied = getRetaFinalOccupiedBlocoIds(state.eventos);
  const rollover = rolloverRetaFinalBlocks(retaFinal, { today, preservedBlocoIds: occupied });

  const blocoById = new Map();
  for (const bloco of retaFinal.blocos || []) {
    if (bloco?.id) blocoById.set(bloco.id, bloco);
  }

  // 3. Wipe: auto pendente cujo bloco não sustenta mais este evento
  // (inexistente, não-pendente, data/duração divergente ou já no passado).
  let wiped = 0;
  state.eventos = state.eventos.filter((ev) => {
    if (!ev?.rfBlocoId || !ev.isAutoGenerated) return true;
    if (isPreservedEvent(ev)) return true;
    const bloco = blocoById.get(ev.rfBlocoId);
    const sustenta =
      bloco &&
      bloco.status === 'pendente' &&
      bloco.data === ev.data &&
      bloco.data >= today &&
      Math.round(Number(ev.duracao) || 0) === Math.round(Number(bloco.minutos) || 0);
    if (sustenta) return true;
    wiped++;
    return false;
  });

  // 3b. Retítulo dos autos sustentados com título obsoleto (ex.: eventos
  // criados antes do título com tópico). Determinístico e re-derivado por
  // dispositivo — nunca carimba ev.updatedAt (anti ping-pong LWW). Eventos
  // preservados (estudei/com tempo) já saíram no isPreservedEvent acima.
  let retitled = 0;
  for (const ev of state.eventos) {
    if (!ev?.rfBlocoId || !ev.isAutoGenerated || isPreservedEvent(ev)) continue;
    const bloco = blocoById.get(ev.rfBlocoId);
    if (!bloco) continue;
    const titulo = buildRetaFinalEventTitle(bloco, findDisciplina(bloco.discId));
    if (ev.titulo !== titulo) {
      ev.titulo = titulo;
      retitled++;
    }
  }

  // 4. Materializa eventos para blocos pendentes de hoje/futuro sem evento.
  const comEvento = new Set();
  for (const ev of state.eventos) {
    if (ev?.rfBlocoId) comEvento.add(ev.rfBlocoId);
  }
  let created = 0;
  for (const bloco of retaFinal.blocos || []) {
    if (!bloco?.id || bloco.status !== 'pendente') continue;
    if (!bloco.data || bloco.data < today) continue;
    if (comEvento.has(bloco.id)) continue;
    const primeiroTopico = (bloco.topicos || [])[0] || null;
    state.eventos.push({
      id: 'autorf_' + uid(),
      titulo: buildRetaFinalEventTitle(bloco, findDisciplina(bloco.discId)),
      data: bloco.data,
      duracao: Math.max(0, Math.round(Number(bloco.minutos) || 0)),
      status: 'agendado',
      tempoAcumulado: 0,
      tipo: 'conteudo',
      discId: bloco.discId || null,
      assId: primeiroTopico?.assId || null,
      aulaId: primeiroTopico?.aulaId || null,
      habito: null,
      rfBlocoId: bloco.id,
      criadoEm: new Date().toISOString(),
      isAutoGenerated: true,
    });
    created++;
  }

  if (reconcile.changed || rollover.changed || wiped > 0 || retitled > 0 || created > 0) {
    scheduleSave();
  }
}

/**
 * "Marcar como estudado" com um clique num bloco pendente: promove o evento
 * auto 'agendado' do bloco para 'estudei' (preservando tempoAcumulado), ou
 * cria um se não existir. A conclusão do bloco continua derivada de eventos —
 * o reconcile dentro de syncRetaFinalToEventos fecha o bloco. Mutação real do
 * usuário: carimba ev.updatedAt (LWW), mas nunca planejamento.updatedAt.
 * Não mexe em hábitos/revisões/aula.estudada — detalhes de tempo/questões são
 * complementados depois editando a sessão no Histórico (edit-session-record).
 * Undo = excluir/editar a sessão no Histórico (reconcile reabre o bloco).
 * @returns {boolean} true se marcou
 */
export function quickCompleteRetaFinalBloco(blocoId) {
  if (!isRetaFinalPlan()) return false;
  const bloco = (state.planejamento.retaFinal.blocos || []).find((b) => b?.id === blocoId);
  if (!bloco || bloco.status !== 'pendente') return false;

  let ev = (state.eventos || []).find((e) => e?.rfBlocoId === blocoId && e.status === 'agendado');
  if (!ev) {
    ev = {
      id: 'autorf_' + uid(),
      titulo: '',
      data: bloco.data,
      duracao: Math.max(0, Math.round(Number(bloco.minutos) || 0)),
      status: 'agendado',
      tempoAcumulado: 0,
      tipo: 'conteudo',
      discId: bloco.discId || null,
      assId: null,
      aulaId: null,
      habito: null,
      rfBlocoId: bloco.id,
      criadoEm: new Date().toISOString(),
      isAutoGenerated: true,
    };
    state.eventos.push(ev);
  }

  ev.titulo = buildRetaFinalEventTitle(bloco, findDisciplina(bloco.discId));
  ev.status = 'estudei';
  ev.dataEstudo = todayStr();
  const topicos = buildTopicosFromRetaFinalBloco(bloco).map((item) => ({
    ...item,
    statusTopico: 'em_andamento',
  }));
  applyTopicosToEvent(ev, topicos);
  ev.updatedAt = new Date().toISOString();

  syncRetaFinalToEventos();
  scheduleSave();
  return true;
}

/**
 * Associa uma sessão do Histórico (evento `estudei` sem vínculo) a um bloco
 * pendente: seta `rfBlocoId` e o reconcile conclui o bloco. Preserva a DATA
 * REAL da sessão (não toca data/dataEstudo) — é o caminho para blocos
 * atrasados/"rolados" já estudados por fora. O auto 'agendado' órfão do bloco
 * é limpo pelo wipe do sync, sem tombstone (autos são re-deriváveis).
 * Mutação real do usuário: carimba ev.updatedAt; nunca planejamento.updatedAt.
 * @returns {boolean} true se associou
 */
export function associateHistoryEventToBloco(blocoId, eventoId) {
  if (!isRetaFinalPlan()) return false;
  const bloco = (state.planejamento.retaFinal.blocos || []).find((b) => b?.id === blocoId);
  if (!bloco || bloco.status !== 'pendente') return false;
  const ev = (state.eventos || []).find((e) => e?.id === eventoId);
  if (!ev || ev.status !== 'estudei' || ev.rfBlocoId) return false;

  ev.rfBlocoId = bloco.id;
  ev.updatedAt = new Date().toISOString();

  syncRetaFinalToEventos();
  scheduleSave();
  return true;
}

/**
 * Remove eventos pendentes derivados de qualquer plano (autos do Ciclo, com
 * seqId ou com rfBlocoId), preservando estudados e com tempo acumulado —
 * mesmo critério de resetCicloAndWipeEvents. Usado na troca de plano
 * (ativação/restauração da Reta Final).
 */
function wipeAutoPlanEvents() {
  state.eventos = (state.eventos || []).filter((ev) => {
    const isPlanned = ev?.isAutoGenerated || Boolean(ev?.seqId) || Boolean(ev?.rfBlocoId);
    if (!isPlanned) return true;
    return ev.status === 'estudei' || Number(ev.tempoAcumulado) > 0;
  });
}

function findDisciplina(discId) {
  for (const edital of state.editais || []) {
    for (const disc of edital?.disciplinas || []) {
      if (disc.id === discId) return disc;
    }
  }
  return null;
}

/**
 * Ativa a Reta Final a partir de um payload validado:
 *  1. cria disciplinas/assuntos/aulas faltantes nos editais (disciplina nova
 *     vai no edital principal ativo, ou num edital "Reta Final" se não houver);
 *  2. arquiva o plano ativo em state.planejamentoArquivado (restaurável após a
 *     dataFinal); re-import sobre uma reta_final preserva o arquivado original;
 *  3. substitui state.planejamento por um plano tipo 'reta_final' com os
 *     blocos dia-a-dia (updatedAt novo: import é mutação real do usuário, ao
 *     contrário da rolagem);
 *  4. limpa autos pendentes do plano anterior e materializa os novos eventos.
 * @param {{ payload: object, matching?: object }} params - matching opcional
 *   (resultado de matchRetaFinalToEditais usado no preview); recalculado se
 *   ausente.
 * @returns {object} o novo state.planejamento
 */
export function activateRetaFinal({ payload, matching } = {}) {
  const validation = validateRetaFinalPayload(payload);
  if (!validation.valid) {
    throw new Error('JSON da Reta Final inválido: ' + validation.errors.join(' '));
  }
  const match = matching || matchRetaFinalToEditais(payload, state.editais);

  // 1. Garante as entidades nos editais.
  if (!Array.isArray(state.editais)) state.editais = [];
  let targetEdital = state.editais.find((e) => e && !e.arquivado) || null;
  const ensureTargetEdital = () => {
    if (!targetEdital) {
      targetEdital = {
        id: uid(),
        nome: 'Reta Final',
        cor: '#0f766e',
        disciplinas: [],
        arquivado: false,
        arquivadoEm: null,
      };
      state.editais.push(targetEdital);
    }
    return targetEdital;
  };

  const resolvedByKey = new Map(); // key da disciplina -> { discId, assIdByKey, aulaIdByKey }
  for (const discMatch of match.disciplinas) {
    let disc = discMatch.discId ? findDisciplina(discMatch.discId) : null;
    if (!disc) {
      const edital = ensureTargetEdital();
      disc = {
        id: uid(),
        nome: discMatch.nome,
        icone: '📚',
        cor: edital.cor || '#0f766e',
        assuntos: [],
        aulas: [],
      };
      edital.disciplinas.push(disc);
    }
    if (!Array.isArray(disc.assuntos)) disc.assuntos = [];
    if (!Array.isArray(disc.aulas)) disc.aulas = [];

    const assIdByKey = new Map();
    for (const topico of discMatch.topicos) {
      let assId = topico.assId;
      if (!assId) {
        const assunto = {
          id: 'ass_' + uid(),
          nome: topico.nome,
          concluido: false,
          dataConclusao: null,
          revisoesFetas: [],
          adiamentos: 0,
          linkedAulaIds: [],
        };
        disc.assuntos.push(assunto);
        assId = assunto.id;
      }
      assIdByKey.set(topico.key, assId);
    }

    const aulaIdByKey = new Map();
    for (const aulaMatch of discMatch.aulas) {
      let aulaId = aulaMatch.aulaId;
      if (!aulaId) {
        const aula = {
          id: 'aula_' + uid(),
          nome: aulaMatch.nome,
          descricao: '',
          estudada: false,
          dataEstudo: null,
          progress: 0,
          linkedAssuntoIds: [],
        };
        disc.aulas.push(aula);
        aulaId = aula.id;
      }
      aulaIdByKey.set(aulaMatch.key, aulaId);
    }

    resolvedByKey.set(discMatch.key, { discId: disc.id, assIdByKey, aulaIdByKey });
  }

  // 2. Monta os blocos dia-a-dia (ordem estável por data).
  const minutosPadrao =
    Number.isInteger(payload.minutosPadrao) && payload.minutosPadrao > 0
      ? payload.minutosPadrao
      : 60;
  const blocos = [];
  const dias = [...payload.dias].sort((a, b) => (a.data < b.data ? -1 : a.data > b.data ? 1 : 0));
  for (const dia of dias) {
    for (const blocoPayload of dia.blocos || []) {
      const resolved = resolvedByKey.get(normalizeNameKey(blocoPayload.disciplina));
      if (!resolved) continue;
      const topicos = [];
      for (const topicoNome of Array.isArray(blocoPayload.topicos) ? blocoPayload.topicos : []) {
        const assId = resolved.assIdByKey.get(normalizeNameKey(topicoNome));
        if (assId) topicos.push({ assId, aulaId: null });
      }
      const aulaId = resolved.aulaIdByKey.get(normalizeNameKey(blocoPayload.aula));
      if (aulaId) topicos.push({ assId: null, aulaId });
      blocos.push({
        id: 'rf_' + uid(),
        data: dia.data,
        dataOriginal: dia.data,
        discId: resolved.discId,
        topicos,
        minutos:
          Number.isInteger(blocoPayload.minutos) && blocoPayload.minutos > 0
            ? blocoPayload.minutos
            : minutosPadrao,
        status: 'pendente',
        rolagens: 0,
      });
    }
  }

  // 3. Arquiva o plano ativo e substitui pelo plano reta_final. Se o plano
  // atual já é uma reta_final (re-import), o arquivado original (pré-reta)
  // é preservado — arquivar a reta antiga o perderia.
  const now = new Date().toISOString();
  const current = state.planejamento;
  if (current?.ativo && current.tipo && current.tipo !== 'reta_final') {
    state.planejamentoArquivado = { plan: deepClone(current), arquivadoEm: now };
  }

  state.planejamento = {
    ativo: true,
    tipo: 'reta_final',
    disciplinas: [...new Set(blocos.map((b) => b.discId))],
    relevancia: {},
    horarios: { dataFinal: payload.dataFinal },
    materiasPorDia: state.config?.materiasPorDia || 3,
    sequencia: [],
    skippedSlots: [],
    slotOverrides: [],
    ciclosCompletos: 0,
    dataInicioCicloAtual: now,
    // Import é mutação real do usuário: reivindica autoria no LWW do plano
    // (equivalente a touchPlanejamento(); não importado de cycle.js para não
    // criar ciclo de imports).
    updatedAt: now,
    retaFinal: {
      nome: String(payload.nome || 'Reta Final'),
      dataFinal: payload.dataFinal,
      minutosPadrao,
      importadoEm: now,
      blocos,
    },
  };

  // 4. Troca de plano: limpa autos pendentes do plano anterior e materializa.
  wipeAutoPlanEvents();
  syncRetaFinalToEventos();
  scheduleSave();
  return state.planejamento;
}

/**
 * Restaura o plano arquivado pela ativação da Reta Final (banner pós-prova).
 * Restauração é mutação real: reivindica autoria no LWW (updatedAt novo) para
 * propagar entre dispositivos. O chamador (camada de ações) deve invalidar
 * caches e re-agendar eventos do plano restaurado (syncCicloToEventos).
 * @returns {boolean} true se restaurou
 */
export function restaurarPlanejamentoArquivado() {
  const arquivado = state.planejamentoArquivado;
  if (!arquivado?.plan) return false;
  const plan = deepClone(arquivado.plan);
  plan.updatedAt = new Date().toISOString();
  state.planejamento = plan;
  state.planejamentoArquivado = null;
  wipeAutoPlanEvents();
  scheduleSave();
  return true;
}
