// =============================================
// RETA FINAL — ORQUESTRAÇÃO (estado + agendador)
// Camada com estado sobre o núcleo puro (reta-final-core.js): materializa os
// blocos do cronograma dia-a-dia como eventos do calendário (rfBlocoId,
// análogo ao seqId do Ciclo). Importada por logic/cycle.js (roteamento de
// syncCicloToEventos) — por isso este módulo só importa store/utils/core,
// nunca cycle.js (evita ciclo de imports).
// =============================================
import { scheduleSave, state } from '../store.js?v=8.37';
import { todayStr, uid } from '../utils.js?v=8.37';
import {
  reconcileRetaFinalWithEvents,
  rolloverRetaFinalBlocks,
} from './reta-final-core.js';

function isRetaFinalPlan(plan = state.planejamento) {
  return Boolean(plan?.ativo && plan.tipo === 'reta_final' && plan.retaFinal);
}

function getDiscNome(discId) {
  for (const edital of state.editais || []) {
    for (const disc of edital?.disciplinas || []) {
      if (disc.id === discId) return disc.nome;
    }
  }
  return null;
}

/**
 * Blocos já consumidos por eventos preservados (sessão estudada ou com tempo
 * acumulado). O agendador não pode re-materializar nem rolar esses blocos —
 * análogo exato do occupiedSlots do Ciclo (bug histórico da "sessão que
 * volta", commit 8756f10).
 * @returns {Set<string>}
 */
export function getRetaFinalOccupiedBlocoIds(eventos = state.eventos) {
  const occupied = new Set();
  for (const ev of eventos || []) {
    if (!ev?.rfBlocoId) continue;
    if (ev.status === 'estudei' || Number(ev.tempoAcumulado) > 0) occupied.add(ev.rfBlocoId);
  }
  return occupied;
}

function isPreservedEvent(ev) {
  return ev.status === 'estudei' || Number(ev.tempoAcumulado) > 0;
}

/**
 * Agendador idempotente da Reta Final (chamado no boot, no render da view e
 * roteado por syncCicloToEventos quando tipo === 'reta_final'):
 *  1. reconcilia blocos com eventos (estudei → concluido);
 *  2. rola blocos atrasados para hoje (pós-dataFinal → nao_coberto);
 *  3. remove autos órfãos não preservados (bloco sumiu/rolou/concluiu);
 *  4. materializa eventos para blocos pendentes de hoje/futuro sem evento.
 * Nunca chama touchPlanejamento() — rolagem/reconcile são views derivadas dos
 * eventos, re-deriváveis em cada dispositivo (anti ping-pong LWW).
 */
export function syncRetaFinalToEventos() {
  if (!isRetaFinalPlan()) return;
  const plan = state.planejamento;
  const retaFinal = plan.retaFinal;
  const today = todayStr();

  const reconcile = reconcileRetaFinalWithEvents(plan, state.eventos);
  const occupied = getRetaFinalOccupiedBlocoIds(state.eventos);
  const rollover = rolloverRetaFinalBlocks(retaFinal, { today, preservedBlocoIds: occupied });

  const blocoById = new Map();
  for (const bloco of retaFinal.blocos || []) {
    if (bloco?.id) blocoById.set(bloco.id, bloco);
  }

  // 3. Wipe: auto pendente cujo bloco não sustenta mais este evento
  // (inexistente, não-pendente, data/duração divergente ou já no passado).
  let wiped = 0;
  state.eventos = state.eventos.filter((ev) => {
    if (!ev?.rfBlocoId || !ev.isAutoGenerated) return true;
    if (isPreservedEvent(ev)) return true;
    const bloco = blocoById.get(ev.rfBlocoId);
    const sustenta =
      bloco &&
      bloco.status === 'pendente' &&
      bloco.data === ev.data &&
      bloco.data >= today &&
      Math.round(Number(ev.duracao) || 0) === Math.round(Number(bloco.minutos) || 0);
    if (sustenta) return true;
    wiped++;
    return false;
  });

  // 4. Materializa eventos para blocos pendentes de hoje/futuro sem evento.
  const comEvento = new Set();
  for (const ev of state.eventos) {
    if (ev?.rfBlocoId) comEvento.add(ev.rfBlocoId);
  }
  let created = 0;
  for (const bloco of retaFinal.blocos || []) {
    if (!bloco?.id || bloco.status !== 'pendente') continue;
    if (!bloco.data || bloco.data < today) continue;
    if (comEvento.has(bloco.id)) continue;
    const primeiroTopico = (bloco.topicos || [])[0] || null;
    state.eventos.push({
      id: 'autorf_' + uid(),
      titulo: `Estudar ${getDiscNome(bloco.discId) || 'Disciplina'}`,
      data: bloco.data,
      duracao: Math.max(0, Math.round(Number(bloco.minutos) || 0)),
      status: 'agendado',
      tempoAcumulado: 0,
      tipo: 'conteudo',
      discId: bloco.discId || null,
      assId: primeiroTopico?.assId || null,
      aulaId: primeiroTopico?.aulaId || null,
      habito: null,
      rfBlocoId: bloco.id,
      criadoEm: new Date().toISOString(),
      isAutoGenerated: true,
    });
    created++;
  }

  if (reconcile.changed || rollover.changed || wiped > 0 || created > 0) {
    scheduleSave();
  }
}
