import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createEdital,
} from '../helpers/state-builders.js';

// Bug real (backup 2026-07-07): após estudar a sessão do slot 0 de hoje, o
// syncCicloToEventos re-preenchia o MESMO slot com um novo evento pendente —
// a "sessão apagada que volta". Slots já ocupados por eventos preservados
// (estudei ou com tempo acumulado) não podem ser reagendados no mesmo dia.

const HOJE = '2026-04-20';

let store;
let logic;

function seqStep(overrides = {}) {
  return {
    id: 'seq_1',
    discId: 'disc_1',
    minutosAlvo: 120,
    concluido: false,
    status: 'pendente',
    ...overrides,
  };
}

function buildState({ eventos = [], sequencia, planOverrides = {} } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({ id: 'disc_1', nome: 'Direito Civil' }),
          createDisciplina({ id: 'disc_2', nome: 'Direito Constitucional' }),
          createDisciplina({ id: 'disc_3', nome: 'Português' }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'ciclo',
      disciplinas: ['disc_1', 'disc_2', 'disc_3'],
      relevancia: {},
      horarios: { dataInicial: '2026-04-01', dataFinal: '2026-04-30' },
      materiasPorDia: 2,
      sequencia: sequencia || [
        seqStep({ id: 'seq_1', discId: 'disc_1' }),
        seqStep({ id: 'seq_2', discId: 'disc_2' }),
        seqStep({ id: 'seq_3', discId: 'disc_3' }),
      ],
      skippedSlots: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-04-01T00:00:00.000Z',
      updatedAt: '2026-04-10T00:00:00.000Z',
      ...planOverrides,
    },
    eventos,
  });
}

function autoEvento(overrides = {}) {
  return createEvento({
    data: HOJE,
    isAutoGenerated: true,
    tipo: 'conteudo',
    ...overrides,
  });
}

function pendentesDoDia(data) {
  return store.state.eventos.filter((e) => e.data === data && e.status !== 'estudei');
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
});

describe('syncCicloToEventos — slots ocupados por eventos preservados', () => {
  it('não re-preenche o slot de hoje ocupado por sessão estudada', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_estudado',
            status: 'estudei',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 57 * 60, // parcial: etapa segue pendente
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();

    const pendentesHoje = pendentesDoDia(HOJE);
    expect(pendentesHoje.filter((e) => e.slotIndex === 0)).toEqual([]);
    // Capacidade do dia: 2 slots, 1 consumido — no máximo 1 pendente novo.
    expect(pendentesHoje.length).toBeLessThanOrEqual(1);
  });

  it('dia com todos os slots consumidos por sessões estudadas não recebe pendentes', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_est_0',
            status: 'estudei',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 30 * 60,
          }),
          autoEvento({
            id: 'ev_est_1',
            status: 'estudei',
            discId: 'disc_2',
            seqId: 'seq_2',
            slotIndex: 1,
            tempoAcumulado: 30 * 60,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();

    expect(pendentesDoDia(HOJE)).toEqual([]);
  });

  it('evento com tempo acumulado (timer parcial) também ocupa o slot', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_parcial',
            status: 'agendado',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 10 * 60,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();

    const slot0 = pendentesDoDia(HOJE).filter((e) => e.slotIndex === 0);
    // Só o próprio evento parcial pode ocupar o slot 0 — nada novo por cima.
    expect(slot0.map((e) => e.id)).toEqual(['ev_parcial']);
  });

  it('slot ocupado + override no outro slot: dia fica sem novos pendentes', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_estudado',
            status: 'estudei',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 57 * 60,
          }),
        ],
        planOverrides: {
          slotOverrides: [
            {
              id: 'slot_x',
              data: HOJE,
              slotIndex: 1,
              seqId: 'seq_2',
              status: 'perdido',
              originalDiscId: 'disc_2',
            },
          ],
        },
      })
    );
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();

    expect(pendentesDoDia(HOJE)).toEqual([]);
  });

  it('previsão do ciclo também não conta slots já ocupados (paridade com o agendador)', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_est_0',
            status: 'estudei',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 30 * 60,
          }),
          autoEvento({
            id: 'ev_est_1',
            status: 'estudei',
            discId: 'disc_2',
            seqId: 'seq_2',
            slotIndex: 1,
            tempoAcumulado: 30 * 60,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    // Projeção só de HOJE: os 2 slots do dia já foram consumidos.
    const projection = logic.calculateCyclePredictionsModel(HOJE, HOJE);
    const totalSessoes = Object.values(projection).reduce((acc, p) => acc + p.sessoes, 0);
    expect(totalSessoes).toBe(0);
  });

  it('fluxo do bug: estudar → regen → apagar o pendente re-criado → nada volta no dia', () => {
    store.setState(
      buildState({
        eventos: [
          autoEvento({
            id: 'ev_estudado',
            status: 'estudei',
            discId: 'disc_1',
            seqId: 'seq_1',
            slotIndex: 0,
            tempoAcumulado: 57 * 60,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();
    const fantasma = pendentesDoDia(HOJE)[0];
    if (fantasma) {
      logic.removeEvento(fantasma.id);
      expect(pendentesDoDia(HOJE)).toEqual([]);
    }

    // Regen extra (boot, virada de view) não pode repovoar o dia.
    logic.syncCicloToEventos();
    expect(pendentesDoDia(HOJE)).toEqual([]);
  });
});
