import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { createAssunto, createBaseState, createDisciplina, createEdital, createEvento } from '../helpers/state-builders.js';
import { loadAppModules } from '../helpers/module-loader.js';

let store;
let logic;

function localDateStr(dateObj = new Date()) {
  const local = new Date(dateObj.getTime() - (dateObj.getTimezoneOffset() * 60000));
  return local.toISOString().slice(0, 10);
}

beforeEach(async () => {
  global.document = {
    dispatchEvent: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    getElementById: () => null,
    querySelector: () => null
  };
  ({ store, logic } = await loadAppModules());
  store.setState(createBaseState());
  logic.invalidateDiscCache();
  logic.invalidateRevCache();
  logic.invalidatePendingRevCache();
  logic.invalidateDashCaches();
  logic.invalidateStreakCache();
});

afterEach(() => {
  delete global.document;
});

describe('logic.js', () => {
  it('calcRevisionDates returns upcoming dates from configured intervals', () => {
    store.setState(createBaseState({
      config: {
        ...createBaseState().config,
        frequenciaRevisao: [1, 7, 30, 90]
      }
    }));

    expect(logic.calcRevisionDates('2026-04-10', [], 0)).toEqual([
      '2026-04-11',
      '2026-04-17',
      '2026-05-10',
      '2026-07-09'
    ]);
  });

  it('getPendingRevisoes returns only concluded topics with due revisions', () => {
    const concluded = createAssunto({
      id: 'ass_due',
      nome: 'Direito Constitucional',
      concluido: true,
      dataConclusao: '2026-04-10',
      revisoesFetas: []
    });
    const pending = createAssunto({
      id: 'ass_not_due',
      nome: 'Direito Penal',
      concluido: false
    });

    store.setState(createBaseState({
      editais: [
        createEdital({
          disciplinas: [
            createDisciplina({
              id: 'disc_1',
              nome: 'Direito',
              assuntos: [concluded, pending]
            })
          ]
        })
      ]
    }));
    logic.invalidateDiscCache();
    logic.invalidateRevCache();
    logic.invalidatePendingRevCache();

    const revisoes = logic.getPendingRevisoes();

    expect(revisoes).toHaveLength(1);
    expect(revisoes[0]).toMatchObject({
      data: '2026-04-11'
    });
    expect(revisoes[0].assunto.id).toBe('ass_due');
  });

  it('calculateRelevanceWeights computes weights and percentages from importance and knowledge', () => {
    const result = logic.calculateRelevanceWeights({
      disc_a: { importancia: 5, conhecimento: 1 },
      disc_b: { importancia: 2, conhecimento: 4 }
    });

    expect(result.disc_a.peso).toBe(25);
    expect(result.disc_b.peso).toBe(4);
    expect(result.disc_a.percentual).toBeCloseTo(86.206, 2);
    expect(result.disc_b.percentual).toBeCloseTo(13.793, 2);
  });

  it('generatePlanejamento stores the plan and creates auto-generated events', () => {
    store.setState(createBaseState({
      editais: [
        createEdital({
          disciplinas: [
            createDisciplina({ id: 'disc_a', nome: 'Português' }),
            createDisciplina({ id: 'disc_b', nome: 'Raciocínio Lógico' })
          ]
        })
      ]
    }));
    logic.invalidateDiscCache();

    const plan = logic.generatePlanejamento({
      tipo: 'ciclo',
      disciplinas: ['disc_a', 'disc_b'],
      relevancia: {
        disc_a: { importancia: 5, conhecimento: 2 },
        disc_b: { importancia: 3, conhecimento: 3 }
      },
      horarios: {
        horasSemanais: 6,
        sessaoMin: 30,
        sessaoMax: 60,
        diasAtivos: []
      }
    });

    expect(plan.ativo).toBe(true);
    expect(plan.sequencia.length).toBeGreaterThan(0);
    expect(store.state.planejamento.ativo).toBe(true);
    expect(store.state.eventos.some((evento) => evento.isAutoGenerated)).toBe(true);
  });

  it('getConsistencyStreak calculates current streak from studied event dates', () => {
    const today = new Date();
    const oneDay = 24 * 60 * 60 * 1000;

    store.setState(createBaseState({
      eventos: [
        createEvento({ id: 'ev_today', status: 'estudei', tempoAcumulado: 1800, dataEstudo: localDateStr(today) }),
        createEvento({ id: 'ev_yesterday', status: 'estudei', tempoAcumulado: 1800, dataEstudo: localDateStr(new Date(today.getTime() - oneDay)) }),
        createEvento({ id: 'ev_two_days', status: 'estudei', tempoAcumulado: 1800, dataEstudo: localDateStr(new Date(today.getTime() - (2 * oneDay))) })
      ]
    }));
    logic.invalidateDashCaches();
    logic.invalidateStreakCache();

    const streak = logic.getConsistencyStreak();

    expect(streak.currentStreak).toBe(3);
    expect(streak.maxStreak).toBeGreaterThanOrEqual(3);
    expect(streak.heatmap).toHaveLength(30);
  });

  it('totalStudySeconds sums accumulated time of studied events', () => {
    store.setState(createBaseState({
      eventos: [
        createEvento({ status: 'estudei', tempoAcumulado: 1000 }),
        createEvento({ status: 'estudei', tempoAcumulado: 2000 }),
        createEvento({ status: 'agendado', tempoAcumulado: 5000 })
      ]
    }));

    expect(logic.totalStudySeconds()).toBe(3000);
  });

  it('getPerformanceStats aggregates total questions across all studied events', () => {
    store.setState(createBaseState({
      eventos: [
        createEvento({ status: 'estudei', questoes: { certas: 10, erradas: 2 } }),
        createEvento({ status: 'estudei', questoes: { certas: 5, erradas: 5 } }),
        createEvento({ status: 'agendado', questoes: { certas: 50, erradas: 0 } })
      ]
    }));
    logic.invalidateDashCaches();

    const stats = logic.getPerformanceStats();
    expect(stats.questionsTotal).toBe(22);
    expect(stats.questionsCorrect).toBe(15);
    expect(stats.questionsWrong).toBe(7);
  });

  it('getSyllabusProgress calculates studied vs total subjects', () => {
    store.setState(createBaseState({
      editais: [
        createEdital({
          disciplinas: [
            createDisciplina({
              aulas: [ { estudada: true }, { estudada: false }, { estudada: true } ]
            })
          ]
        })
      ]
    }));
    logic.invalidateDashCaches();

    const progress = logic.getSyllabusProgress();
    expect(progress.totalAssuntos).toBe(3);
    expect(progress.totalConcluidos).toBe(2);
  });
});
