import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// Iniciar o cronômetro de um bloco da Reta Final (Foco de Hoje / cronograma):
// o bloco pendente resolve para o evento espelhado (rfBlocoId) via
// getRetaFinalBlocoEvento, e getActiveTimerEventIds lista os timers ativos
// para a confirmação "pausar sessão em andamento?".

const HOJE = '2026-07-10';
const ONTEM = '2026-07-09';

let store;
let logic;
let retaFinalMod;
let timerMod;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos, planOverrides = {} } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
      ...planOverrides,
    },
    eventos,
  });
}

function autoEvento(overrides = {}) {
  return createEvento({
    id: 'autorf_existente',
    titulo: 'Estudar Direito Penal',
    data: HOJE,
    duracao: 90,
    status: 'agendado',
    tempoAcumulado: 0,
    discId: 'disc_1',
    assId: 'ass_1',
    aulaId: null,
    rfBlocoId: 'rf_1',
    isAutoGenerated: true,
    ...overrides,
  });
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  retaFinalMod = await import('../../src/js/logic/reta-final.js');
  timerMod = await import('../../src/js/logic/timer.js');
});

describe('getRetaFinalBlocoEvento', () => {
  it('retorna o evento agendado espelhado do bloco pendente', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();

    const ev = retaFinalMod.getRetaFinalBlocoEvento('rf_1');

    expect(ev).not.toBeNull();
    expect(ev.id).toBe('autorf_existente');
    expect(ev.status).toBe('agendado');
  });

  it('materializa o evento quando o bloco ainda não tem nenhum', () => {
    store.setState(buildState());
    logic.invalidateDiscCache();

    const ev = retaFinalMod.getRetaFinalBlocoEvento('rf_1');

    expect(ev).not.toBeNull();
    expect(ev.rfBlocoId).toBe('rf_1');
    expect(ev.status).toBe('agendado');
    expect(store.state.eventos.filter((e) => e.rfBlocoId === 'rf_1')).toHaveLength(1);
  });

  it('bloco atrasado é rolado para hoje e ganha evento', () => {
    store.setState(
      buildState({ blocos: [rfBloco({ data: ONTEM, dataOriginal: ONTEM })] })
    );
    logic.invalidateDiscCache();

    const ev = retaFinalMod.getRetaFinalBlocoEvento('rf_1');

    expect(ev).not.toBeNull();
    expect(ev.data).toBe(HOJE);
    expect(ev.status).toBe('agendado');
  });

  it('retorna null para bloco concluído, inexistente ou plano não reta_final', () => {
    store.setState(buildState({ blocos: [rfBloco({ status: 'concluido' })] }));
    logic.invalidateDiscCache();
    expect(retaFinalMod.getRetaFinalBlocoEvento('rf_1')).toBeNull();
    expect(retaFinalMod.getRetaFinalBlocoEvento('rf_sumiu')).toBeNull();

    store.setState(buildState({ planOverrides: { tipo: 'ciclo', retaFinal: undefined } }));
    logic.invalidateDiscCache();
    expect(retaFinalMod.getRetaFinalBlocoEvento('rf_1')).toBeNull();
  });
});

describe('getActiveTimerEventIds', () => {
  it('vazio quando nenhum timer está rodando', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    expect(timerMod.getActiveTimerEventIds()).toEqual([]);
  });

  it('lista eventos com _timerStart e o crono_livre ativo', () => {
    const state = buildState({
      eventos: [
        autoEvento({ id: 'ev_a', rfBlocoId: null, _timerStart: Date.now() }),
        autoEvento({ id: 'ev_b', rfBlocoId: null }),
      ],
    });
    state.cronoLivre = { _timerStart: Date.now(), tempoAcumulado: 0 };
    store.setState(state);

    expect(timerMod.getActiveTimerEventIds()).toEqual(['crono_livre', 'ev_a']);
  });

  it('crono_livre pausado (sem _timerStart) não conta', () => {
    const state = buildState({ eventos: [] });
    state.cronoLivre = { _timerStart: null, tempoAcumulado: 300 };
    store.setState(state);
    expect(timerMod.getActiveTimerEventIds()).toEqual([]);
  });
});
