import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// Quick-mark: "Marcar como estudado" com um clique num bloco pendente da Reta
// Final. A conclusão continua derivada de eventos (reconcile) — o quick-mark
// só cria/promove o evento para 'estudei' e deixa o sync fazer o resto.

const HOJE = '2026-07-10';

let store;
let logic;
let retaFinalMod;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos, planOverrides = {} } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
      ...planOverrides,
    },
    eventos,
  });
}

function autoEvento(overrides = {}) {
  return createEvento({
    id: 'autorf_existente',
    titulo: 'Estudar Direito Penal',
    data: HOJE,
    duracao: 90,
    status: 'agendado',
    tempoAcumulado: 0,
    discId: 'disc_1',
    assId: 'ass_1',
    aulaId: null,
    rfBlocoId: 'rf_1',
    isAutoGenerated: true,
    ...overrides,
  });
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  retaFinalMod = await import('../../src/js/logic/reta-final.js');
});

describe('quickCompleteRetaFinalBloco', () => {
  it('reusa o evento auto agendado do bloco (id estável, tempoAcumulado preservado)', () => {
    store.setState(buildState({ eventos: [autoEvento({ tempoAcumulado: 15 * 60 })] }));
    logic.invalidateDiscCache();

    const ok = retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    expect(ok).toBe(true);
    const eventos = store.state.eventos.filter((e) => e.rfBlocoId === 'rf_1');
    expect(eventos).toHaveLength(1);
    expect(eventos[0].id).toBe('autorf_existente');
    expect(eventos[0].status).toBe('estudei');
    expect(eventos[0].tempoAcumulado).toBe(15 * 60);
  });

  it('cria evento quando o bloco não tem nenhum', () => {
    store.setState(buildState());
    logic.invalidateDiscCache();

    const ok = retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    expect(ok).toBe(true);
    const eventos = store.state.eventos.filter((e) => e.rfBlocoId === 'rf_1');
    expect(eventos).toHaveLength(1);
    expect(eventos[0].id).toMatch(/^autorf_/);
    expect(eventos[0].status).toBe('estudei');
    expect(eventos[0].duracao).toBe(90);
  });

  it('preenche dataEstudo de hoje, título com tópico e sessao.topicos do bloco', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();

    retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    const ev = store.state.eventos.find((e) => e.id === 'autorf_existente');
    expect(ev.dataEstudo).toBe(HOJE);
    expect(ev.titulo).toBe('Direito Penal — Crimes contra a vida');
    expect(ev.sessao.topicos).toEqual([
      {
        assId: 'ass_1',
        aulaId: null,
        questoes: null,
        paginas: null,
        statusTopico: 'em_andamento',
      },
    ]);
    expect(ev.assId).toBe('ass_1');
  });

  it('carimba ev.updatedAt (mutação real) mas NÃO toca planejamento.updatedAt', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();

    retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    const ev = store.state.eventos.find((e) => e.id === 'autorf_existente');
    expect(ev.updatedAt).toBe(new Date().toISOString());
    expect(store.state.planejamento.updatedAt).toBe('2026-07-07T10:00:00.000Z');
  });

  it('bloco vira concluido via reconcile e sync não re-materializa auto por cima', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();

    retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('concluido');

    // Guarda contra a classe do bug "sessão que volta": novo sync não recria
    // evento 'agendado' para o bloco concluído.
    retaFinalMod.syncRetaFinalToEventos();
    const eventos = store.state.eventos.filter((e) => e.rfBlocoId === 'rf_1');
    expect(eventos).toHaveLength(1);
    expect(eventos[0].status).toBe('estudei');
  });

  it('não mexe em hábitos, revisões nem aula.estudada', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();

    retaFinalMod.quickCompleteRetaFinalBloco('rf_1');

    expect(store.state.habitos.questoes).toEqual([]);
    expect(store.state.revisoes).toEqual([]);
    const disc = store.state.editais[0].disciplinas[0];
    expect(disc.assuntos[0].concluido).toBe(false);
  });

  it('retorna false para bloco concluido, nao_coberto ou inexistente', () => {
    store.setState(
      buildState({
        blocos: [
          rfBloco({ id: 'rf_ok', status: 'concluido' }),
          rfBloco({ id: 'rf_nc', status: 'nao_coberto' }),
        ],
      })
    );
    logic.invalidateDiscCache();

    expect(retaFinalMod.quickCompleteRetaFinalBloco('rf_ok')).toBe(false);
    expect(retaFinalMod.quickCompleteRetaFinalBloco('rf_nc')).toBe(false);
    expect(retaFinalMod.quickCompleteRetaFinalBloco('rf_sumiu')).toBe(false);
    expect(store.state.eventos.filter((e) => e?.status === 'estudei')).toHaveLength(0);
  });

  it('retorna false quando o plano ativo não é reta_final', () => {
    store.setState(buildState({ planOverrides: { tipo: 'ciclo', retaFinal: undefined } }));
    logic.invalidateDiscCache();

    expect(retaFinalMod.quickCompleteRetaFinalBloco('rf_1')).toBe(false);
  });

  it('undo: excluir a sessão e re-sincronizar reabre o bloco', () => {
    store.setState(buildState({ eventos: [autoEvento()] }));
    logic.invalidateDiscCache();
    retaFinalMod.quickCompleteRetaFinalBloco('rf_1');
    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('concluido');

    store.state.eventos = store.state.eventos.filter((e) => e.id !== 'autorf_existente');
    retaFinalMod.syncRetaFinalToEventos();

    const bloco = store.state.planejamento.retaFinal.blocos[0];
    expect(bloco.status).toBe('pendente');
    // Reaberto e pendente de hoje: o agendador materializa um novo auto.
    const eventos = store.state.eventos.filter((e) => e.rfBlocoId === 'rf_1');
    expect(eventos).toHaveLength(1);
    expect(eventos[0].status).toBe('agendado');
  });
});
