import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// Associar sessão do Histórico a um bloco pendente: vincula (rfBlocoId) uma
// sessão estudada existente — útil para blocos atrasados já estudados por
// fora — preservando a DATA REAL da sessão. O reconcile fecha o bloco.

const HOJE = '2026-07-10';

let store;
let logic;
let retaFinalMod;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
    },
    eventos,
  });
}

function sessaoManual(overrides = {}) {
  return createEvento({
    id: 'ev_manual',
    titulo: 'Sessão avulsa de Penal',
    data: '2026-07-05',
    dataEstudo: '2026-07-05',
    status: 'estudei',
    tempoAcumulado: 45 * 60,
    discId: 'disc_1',
    assId: 'ass_1',
    ...overrides,
  });
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  retaFinalMod = await import('../../src/js/logic/reta-final.js');
});

describe('associateHistoryEventToBloco', () => {
  it('vincula a sessão, carimba updatedAt e conclui o bloco via reconcile', () => {
    store.setState(buildState({ eventos: [sessaoManual()] }));
    logic.invalidateDiscCache();

    const ok = retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_manual');

    expect(ok).toBe(true);
    const ev = store.state.eventos.find((e) => e.id === 'ev_manual');
    expect(ev.rfBlocoId).toBe('rf_1');
    expect(ev.updatedAt).toBe(new Date().toISOString());
    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('concluido');
  });

  it('preserva a data real: não altera dataEstudo nem data da sessão', () => {
    store.setState(buildState({ eventos: [sessaoManual()] }));
    logic.invalidateDiscCache();

    retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_manual');

    const ev = store.state.eventos.find((e) => e.id === 'ev_manual');
    expect(ev.dataEstudo).toBe('2026-07-05');
    expect(ev.data).toBe('2026-07-05');
  });

  it('NÃO toca planejamento.updatedAt', () => {
    store.setState(buildState({ eventos: [sessaoManual()] }));
    logic.invalidateDiscCache();

    retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_manual');

    expect(store.state.planejamento.updatedAt).toBe('2026-07-07T10:00:00.000Z');
  });

  it('auto agendado órfão do bloco some no sync SEM ganhar tombstone', () => {
    store.setState(
      buildState({
        eventos: [
          sessaoManual(),
          createEvento({
            id: 'autorf_orfao',
            data: HOJE,
            duracao: 90,
            status: 'agendado',
            tempoAcumulado: 0,
            discId: 'disc_1',
            rfBlocoId: 'rf_1',
            isAutoGenerated: true,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_manual');

    expect(store.state.eventos.some((e) => e.id === 'autorf_orfao')).toBe(false);
    expect(store.state.syncTombstones || []).toEqual([]);
  });

  it('retorna false para bloco inexistente/não-pendente e evento inexistente', () => {
    store.setState(
      buildState({
        blocos: [rfBloco(), rfBloco({ id: 'rf_done', status: 'concluido' })],
        eventos: [sessaoManual()],
      })
    );
    logic.invalidateDiscCache();

    expect(retaFinalMod.associateHistoryEventToBloco('rf_sumiu', 'ev_manual')).toBe(false);
    expect(retaFinalMod.associateHistoryEventToBloco('rf_done', 'ev_manual')).toBe(false);
    expect(retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_sumiu')).toBe(false);
    const ev = store.state.eventos.find((e) => e.id === 'ev_manual');
    expect(ev.rfBlocoId).toBeUndefined();
  });

  it('retorna false para evento já vinculado ou não estudado', () => {
    store.setState(
      buildState({
        eventos: [
          sessaoManual({ id: 'ev_vinculado', rfBlocoId: 'rf_outro' }),
          sessaoManual({ id: 'ev_pendente', status: 'agendado' }),
        ],
      })
    );
    logic.invalidateDiscCache();

    expect(retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_vinculado')).toBe(false);
    expect(retaFinalMod.associateHistoryEventToBloco('rf_1', 'ev_pendente')).toBe(false);
    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('pendente');
  });
});
