import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';
import {
  computeRetaFinalHeaderMetrics,
} from '../../src/js/logic/reta-final-core.js';

// Redesign da Reta Final: cabeçalho com 4 KPIs (Concluído %, Faltam dias,
// Horas restante/total, Ritmo necessário), painel "Foco de Hoje" e
// "Distribuição de Horas" em barras. Este arquivo cobre a camada de render.

vi.mock('../../src/js/app.js?v=8.37', () => ({
  openModal: vi.fn(),
  closeModal: vi.fn(),
  showToast: vi.fn(),
  showConfirm: vi.fn(),
  navigate: vi.fn(),
  currentView: 'ciclo',
}));

vi.mock('../../src/js/components.js?v=8.37', () => ({
  renderCurrentView: vi.fn(),
  updateBadges: vi.fn(),
}));

const HOJE = '2026-07-10';
const DATA_FINAL = '2026-08-11'; // 32 dias
const FUTURO = '2026-07-12';
const PASSADO = '2026-07-08';

let store;
let logic;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 60,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos, dataProva = '2026-08-11' } = {}) {
  const base = createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            cor: '#ef7777',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
          createDisciplina({
            id: 'disc_2',
            nome: 'Português',
            cor: '#7dd3a8',
            assuntos: [createAssunto({ id: 'ass_2', nome: 'Crase' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1', 'disc_2'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final TJCE 2026',
        dataFinal: DATA_FINAL,
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
    },
    eventos,
  });
  base.config.dataProva = dataProva;
  return base;
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  document.body.innerHTML = '';
});

async function renderInto(state) {
  store.setState(state);
  logic.invalidateDiscCache();
  const view = await import('../../src/js/views/reta-final-view.js?v=8.37');
  const el = document.createElement('div');
  document.body.appendChild(el);
  view.renderRetaFinal(el, store.state.planejamento);
  return { el, view };
}

function kpi(el, name) {
  return el.querySelector(`[data-kpi="${name}"]`);
}

describe('formatHours', () => {
  it('formata horas inteiras e decimais (pt-BR)', async () => {
    const { formatHours } = await import('../../src/js/views/reta-final-view.js?v=8.37');
    expect(formatHours(0)).toBe('0h');
    expect(formatHours(60)).toBe('1h');
    expect(formatHours(30)).toBe('0,5h');
    expect(formatHours(204)).toBe('3,4h');
    expect(formatHours(6480)).toBe('108h');
  });
});

describe('renderRetaFinal — cabeçalho de KPIs', () => {
  function stateComMetricas() {
    return buildState({
      blocos: [
        rfBloco({ id: 'a', discId: 'disc_1', status: 'concluido', minutos: 60 }),
        rfBloco({ id: 'b', discId: 'disc_1', status: 'concluido', minutos: 60 }),
        rfBloco({ id: 'c', discId: 'disc_1', status: 'pendente', minutos: 60 }),
        rfBloco({ id: 'd', discId: 'disc_2', status: 'pendente', minutos: 60 }),
      ],
      eventos: [
        createEvento({
          id: 'ev_a',
          data: HOJE,
          status: 'estudei',
          tempoAcumulado: 3600,
          discId: 'disc_1',
          rfBlocoId: 'a',
          isAutoGenerated: true,
        }),
        createEvento({
          id: 'ev_b',
          data: HOJE,
          status: 'estudei',
          tempoAcumulado: 3600,
          discId: 'disc_1',
          rfBlocoId: 'b',
          isAutoGenerated: true,
        }),
      ],
    });
  }

  it('renderiza os 4 cards de KPI', async () => {
    const { el } = await renderInto(stateComMetricas());
    expect(kpi(el, 'concluido')).toBeTruthy();
    expect(kpi(el, 'faltam')).toBeTruthy();
    expect(kpi(el, 'horas')).toBeTruthy();
    expect(kpi(el, 'ritmo')).toBeTruthy();
  });

  it('Concluído mostra percentual e blocos', async () => {
    const state = stateComMetricas();
    const { el } = await renderInto(state);
    const m = computeRetaFinalHeaderMetrics(state.planejamento.retaFinal, {
      hoje: HOJE,
      dataProva: state.config.dataProva,
    });
    const card = kpi(el, 'concluido');
    expect(m.percConcluido).toBe(50);
    expect(card.textContent).toContain('50%');
    expect(card.textContent).toContain('2/4');
    // donut recebe o percentual via custom property
    expect(el.querySelector('.rf-donut')).toBeTruthy();
  });

  it('Faltam mostra dias para a prova', async () => {
    const { el } = await renderInto(stateComMetricas());
    const card = kpi(el, 'faltam');
    expect(card.textContent).toContain('32');
    expect(card.textContent.toLowerCase()).toContain('prova');
  });

  it('Horas mostra restante e "Xh de Yh"', async () => {
    const { el } = await renderInto(stateComMetricas());
    const card = kpi(el, 'horas');
    // restantes 120min = 2h; total 240min = 4h; concluído 120min = 2h
    expect(card.textContent).toContain('2h');
    expect(card.textContent).toContain('2h de 4h');
  });

  it('Ritmo usa formatHours(ritmoMinutosPorDia)', async () => {
    const state = stateComMetricas();
    const { el, view } = await renderInto(state);
    const m = computeRetaFinalHeaderMetrics(state.planejamento.retaFinal, {
      hoje: HOJE,
      dataProva: state.config.dataProva,
    });
    const card = kpi(el, 'ritmo');
    expect(card.textContent).toContain(view.formatHours(m.ritmoMinutosPorDia));
  });
});

describe('renderRetaFinal — painel Foco de Hoje', () => {
  function focoBlocoIds(el) {
    return [...el.querySelectorAll('.rf-foco-card .rf-bloco-card')].map(
      (c) => c.dataset.blocoId
    );
  }

  it('lista só os blocos pendentes de hoje e atrasados', async () => {
    const state = buildState({
      blocos: [
        rfBloco({ id: 'rf_done', status: 'concluido' }),
        rfBloco({ id: 'rf_rolado', dataOriginal: PASSADO, rolagens: 1 }),
        rfBloco({ id: 'rf_hoje' }),
        rfBloco({ id: 'rf_fut', data: FUTURO, dataOriginal: FUTURO }),
      ],
      eventos: [
        createEvento({
          id: 'ev_done',
          data: HOJE,
          status: 'estudei',
          tempoAcumulado: 3600,
          discId: 'disc_1',
          rfBlocoId: 'rf_done',
          isAutoGenerated: true,
        }),
      ],
    });
    const { el } = await renderInto(state);
    expect(focoBlocoIds(el)).toEqual(['rf_rolado', 'rf_hoje']);
  });

  it('cabeçalho mostra contagem e total de horas do dia', async () => {
    const state = buildState({
      blocos: [
        rfBloco({ id: 'rf_hoje', minutos: 60 }),
        rfBloco({ id: 'rf_rolado', dataOriginal: PASSADO, rolagens: 1, minutos: 60 }),
      ],
    });
    const { el } = await renderInto(state);
    const header = el.querySelector('.rf-foco-header');
    expect(header).toBeTruthy();
    expect(header.textContent).toContain('2 blocos');
    expect(header.textContent).toContain('2h');
  });

  it('some quando não há bloco pendente de hoje/atrasado', async () => {
    const state = buildState({
      blocos: [rfBloco({ id: 'rf_fut', data: FUTURO, dataOriginal: FUTURO })],
    });
    const { el } = await renderInto(state);
    expect(el.querySelector('.rf-foco-card')).toBeNull();
  });
});

describe('renderRetaFinal — anatomia padronizada das seções', () => {
  function stateComTodasSecoes() {
    return buildState({
      blocos: [
        rfBloco({ id: 'rf_hoje' }),
        rfBloco({ id: 'rf_nc', status: 'nao_coberto' }),
      ],
    });
  }

  it('Foco de Hoje usa header/título padronizados e blocos dentro do corpo', async () => {
    const { el } = await renderInto(stateComTodasSecoes());
    const foco = el.querySelector('.rf-foco-card');
    expect(foco).toBeTruthy();
    expect(foco.querySelector('.rf-section-header.rf-foco-header')).toBeTruthy();
    expect(foco.querySelector('.rf-section-title.rf-foco-title')).toBeTruthy();
    expect(foco.querySelectorAll('.rf-section-body .rf-bloco-card').length).toBe(1);
  });

  it('Cronograma usa o mesmo header/título padronizados', async () => {
    const { el } = await renderInto(stateComTodasSecoes());
    const cronograma = [...el.querySelectorAll('.ciclo-sequence-card')].find((s) =>
      s.textContent.includes('Cronograma dia a dia')
    );
    expect(cronograma).toBeTruthy();
    expect(cronograma.querySelector('.rf-section-header')).toBeTruthy();
    expect(cronograma.querySelector('.rf-section-title')).toBeTruthy();
  });

  it('Não cobertos usa header padronizado e blocos dentro do corpo', async () => {
    const { el } = await renderInto(stateComTodasSecoes());
    const nc = [...el.querySelectorAll('.ciclo-sequence-card')].find((s) =>
      s.textContent.includes('Não cobertos')
    );
    expect(nc).toBeTruthy();
    expect(nc.querySelector('.rf-section-header')).toBeTruthy();
    expect(nc.querySelector('.rf-section-title')).toBeTruthy();
    expect(nc.querySelectorAll('.rf-section-body .rf-bloco-card').length).toBe(1);
  });
});

describe('renderRetaFinal — Distribuição de Horas (barras)', () => {
  function distState() {
    return buildState({
      blocos: [
        rfBloco({ id: 'a', discId: 'disc_1', status: 'concluido', minutos: 60 }),
        rfBloco({ id: 'b', discId: 'disc_1', status: 'pendente', minutos: 60 }),
        rfBloco({ id: 'c', discId: 'disc_2', status: 'pendente', minutos: 60 }),
      ],
      eventos: [
        createEvento({
          id: 'ev_a',
          data: HOJE,
          status: 'estudei',
          tempoAcumulado: 3600,
          discId: 'disc_1',
          rfBlocoId: 'a',
          isAutoGenerated: true,
        }),
      ],
    });
  }

  it('renderiza uma barra por disciplina com o título da seção', async () => {
    const { el } = await renderInto(distState());
    const rows = el.querySelectorAll('.rf-dist-row');
    expect(rows.length).toBe(2);
    expect(el.querySelector('.ciclo-side-panel').textContent).toContain('DISTRIBUIÇÃO DE HORAS');
  });

  it('a barra mostra "Xh de Yh" e largura proporcional ao concluído', async () => {
    const { el } = await renderInto(distState());
    const linhaPenal = [...el.querySelectorAll('.rf-dist-row')].find((r) =>
      r.textContent.includes('Direito Penal')
    );
    expect(linhaPenal).toBeTruthy();
    // disc_1: 1h concluída de 2h → 50%
    expect(linhaPenal.querySelector('.rf-dist-meta').textContent).toContain('1h de 2h');
    expect(linhaPenal.querySelector('.rf-dist-fill').getAttribute('style')).toContain('50%');
  });

  it('mostra o Total restante', async () => {
    const { el } = await renderInto(distState());
    const total = el.querySelector('.rf-dist-total');
    expect(total).toBeTruthy();
    // restantes: 60 (disc_1) + 60 (disc_2) = 120min = 2h
    expect(total.textContent).toContain('Total restante');
    expect(total.textContent).toContain('2h');
  });
});
