import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// Filtro do cronograma dia a dia da Reta Final: seletor EXCLUSIVO (uma visão
// por vez) com "Todos", "Atrasados", "Próximos dias" e "Concluídos", nessa
// ordem, abaixo do título. Estado do filtro vive no módulo da view (sessão).

vi.mock('../../src/js/app.js?v=8.37', () => ({
  openModal: vi.fn(),
  closeModal: vi.fn(),
  showToast: vi.fn(),
  showConfirm: vi.fn(),
  navigate: vi.fn(),
  currentView: 'ciclo',
}));

vi.mock('../../src/js/components.js?v=8.37', () => ({
  renderCurrentView: vi.fn(),
  updateBadges: vi.fn(),
}));

const HOJE = '2026-07-10';
const FUTURO = '2026-07-12';
const PASSADO = '2026-07-08';

let store;
let logic;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
    },
    eventos,
  });
}

// Um bloco de cada categoria: concluído (com evento de sustentação para o
// reconcile não reabrir), atrasado (rolado para hoje), de hoje e futuro.
function buildStateComCategorias() {
  return buildState({
    blocos: [
      rfBloco({ id: 'rf_done', status: 'concluido' }),
      rfBloco({ id: 'rf_rolado', dataOriginal: PASSADO, rolagens: 1 }),
      rfBloco({ id: 'rf_hoje' }),
      rfBloco({ id: 'rf_fut', data: FUTURO, dataOriginal: FUTURO }),
    ],
    eventos: [
      createEvento({
        id: 'ev_done',
        data: HOJE,
        status: 'estudei',
        tempoAcumulado: 3600,
        discId: 'disc_1',
        rfBlocoId: 'rf_done',
        isAutoGenerated: true,
      }),
    ],
  });
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  document.body.innerHTML = '';
});

async function renderInto(state) {
  store.setState(state);
  logic.invalidateDiscCache();
  const view = await import('../../src/js/views/reta-final-view.js?v=8.37');
  const el = document.createElement('div');
  document.body.appendChild(el);
  view.renderRetaFinal(el, store.state.planejamento);
  return { el, view };
}

function cardIds(el) {
  return [...el.querySelectorAll('#rf-dias-lista .rf-bloco-card')].map(
    (card) => card.dataset.blocoId
  );
}

function pressedFiltros(el) {
  return [...el.querySelectorAll('[data-action="rf-set-filtro"]')]
    .filter((b) => b.getAttribute('aria-pressed') === 'true')
    .map((b) => b.dataset.filtro);
}

describe('getRetaFinalBlocoFiltroCategoria — categorização pura', () => {
  it('classifica concluído, atrasado (rolado ou data passada), hoje e futuro', async () => {
    const { getRetaFinalBlocoFiltroCategoria } = await import(
      '../../src/js/logic/reta-final-core.js'
    );

    expect(getRetaFinalBlocoFiltroCategoria(rfBloco({ status: 'concluido' }), HOJE)).toBe(
      'concluido'
    );
    expect(
      getRetaFinalBlocoFiltroCategoria(rfBloco({ dataOriginal: PASSADO, rolagens: 1 }), HOJE)
    ).toBe('atrasado');
    expect(
      getRetaFinalBlocoFiltroCategoria(rfBloco({ data: PASSADO, dataOriginal: PASSADO }), HOJE)
    ).toBe('atrasado');
    expect(getRetaFinalBlocoFiltroCategoria(rfBloco(), HOJE)).toBe('hoje');
    expect(
      getRetaFinalBlocoFiltroCategoria(rfBloco({ data: FUTURO, dataOriginal: FUTURO }), HOJE)
    ).toBe('futuro');
  });
});

describe('renderRetaFinal — seletor de filtro do cronograma', () => {
  it('renderiza Todos, Atrasados, Próximos dias e Concluídos, nessa ordem, com "Todos" ativo', async () => {
    const { el } = await renderInto(buildStateComCategorias());

    const botoes = [...el.querySelectorAll('[data-action="rf-set-filtro"]')];
    expect(botoes.map((b) => b.dataset.filtro)).toEqual([
      'todos',
      'atrasados',
      'proximos',
      'concluidos',
    ]);
    expect(botoes.map((b) => b.textContent.trim())).toEqual([
      'Todos',
      'Atrasados',
      'Próximos dias',
      'Concluídos',
    ]);
    for (const botao of botoes) {
      expect(botao.getAttribute('type')).toBe('button');
    }
    expect(pressedFiltros(el)).toEqual(['todos']);
  });

  it('"Todos" mostra todos os blocos do cronograma', async () => {
    const { el } = await renderInto(buildStateComCategorias());
    expect(cardIds(el)).toEqual(['rf_done', 'rf_rolado', 'rf_hoje', 'rf_fut']);
  });

  it('"Atrasados" mostra só blocos rolados/atrasados pendentes', async () => {
    const { el, view } = await renderInto(buildStateComCategorias());
    view.setRetaFinalFiltro('atrasados');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(cardIds(el)).toEqual(['rf_rolado']);
    expect(pressedFiltros(el)).toEqual(['atrasados']);
  });

  it('"Próximos dias" mostra só os blocos de dias futuros', async () => {
    const { el, view } = await renderInto(buildStateComCategorias());
    view.setRetaFinalFiltro('proximos');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(cardIds(el)).toEqual(['rf_fut']);
    expect(el.querySelector('#rf-dias-lista').textContent).not.toContain('HOJE');
  });

  it('"Concluídos" mostra só blocos concluídos (sem os de hoje)', async () => {
    const { el, view } = await renderInto(buildStateComCategorias());
    view.setRetaFinalFiltro('concluidos');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(cardIds(el)).toEqual(['rf_done']);
  });

  it('voltar para "Todos" mostra tudo de novo', async () => {
    const { el, view } = await renderInto(buildStateComCategorias());
    view.setRetaFinalFiltro('concluidos');
    view.setRetaFinalFiltro('todos');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(cardIds(el)).toEqual(['rf_done', 'rf_rolado', 'rf_hoje', 'rf_fut']);
  });

  it('filtro sem resultados mostra mensagem de vazio do filtro', async () => {
    const { el, view } = await renderInto(
      buildState({ blocos: [rfBloco({ id: 'rf_hoje' })] })
    );
    view.setRetaFinalFiltro('concluidos');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(cardIds(el)).toEqual([]);
    expect(el.querySelector('#rf-dias-lista').textContent).toContain('filtro');
  });

  it('filtro desconhecido é ignorado (mantém o atual)', async () => {
    const { el, view } = await renderInto(buildStateComCategorias());
    view.setRetaFinalFiltro('banana');
    view.renderRetaFinal(el, store.state.planejamento);

    expect(pressedFiltros(el)).toEqual(['todos']);
    expect(cardIds(el)).toEqual(['rf_done', 'rf_rolado', 'rf_hoje', 'rf_fut']);
  });
});

describe('ação rf-set-filtro', () => {
  it('seleciona o filtro e re-renderiza a view', async () => {
    await renderInto(buildStateComCategorias());
    const { actions } = await import('../../src/js/ui/actions/dispatcher.js');
    await import('../../src/js/ui/actions/reta-final.js?v=8.37');
    const components = await import('../../src/js/components.js?v=8.37');

    const botao = document.querySelector(
      '[data-action="rf-set-filtro"][data-filtro="atrasados"]'
    );
    await actions['rf-set-filtro'](botao);

    expect(components.renderCurrentView).toHaveBeenCalled();

    const view = await import('../../src/js/views/reta-final-view.js?v=8.37');
    const el = document.createElement('div');
    view.renderRetaFinal(el, store.state.planejamento);
    expect(cardIds(el)).toEqual(['rf_rolado']);
  });
});
