import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// UI da Reta Final: botões "Marcar como estudado" (✓) e "Associar sessão do
// histórico" (🔗) só em cards pendentes, e picker de associação reusando o
// #modal-prompt (padrão de openSubstitutionPrompt).

vi.mock('../../src/js/app.js?v=8.37', () => ({
  openModal: vi.fn(),
  closeModal: vi.fn(),
  showToast: vi.fn(),
  showConfirm: vi.fn(),
  navigate: vi.fn(),
  currentView: 'ciclo',
}));

vi.mock('../../src/js/components.js?v=8.37', () => ({
  renderCurrentView: vi.fn(),
  updateBadges: vi.fn(),
}));

const HOJE = '2026-07-10';

let store;
let logic;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
    },
    eventos,
  });
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  document.body.innerHTML = '';
});

describe('renderRetaFinal — botões de ação nos cards', () => {
  async function renderInto(state) {
    store.setState(state);
    logic.invalidateDiscCache();
    const { renderRetaFinal } = await import('../../src/js/views/reta-final-view.js?v=8.37');
    const el = document.createElement('div');
    document.body.appendChild(el);
    renderRetaFinal(el, store.state.planejamento);
    return el;
  }

  it('card pendente tem rf-quick-mark e rf-associar-historico com data-bloco-id', async () => {
    const el = await renderInto(buildState());

    const quick = el.querySelector('[data-action="rf-quick-mark"]');
    const assoc = el.querySelector('[data-action="rf-associar-historico"]');
    expect(quick).not.toBeNull();
    expect(assoc).not.toBeNull();
    expect(quick.dataset.blocoId).toBe('rf_1');
    expect(assoc.dataset.blocoId).toBe('rf_1');
    expect(quick.getAttribute('type')).toBe('button');
    expect(assoc.getAttribute('type')).toBe('button');
  });

  it('cards concluído e não coberto NÃO ganham botões de ação', async () => {
    const el = await renderInto(
      buildState({
        blocos: [
          rfBloco({ id: 'rf_done', status: 'concluido' }),
          rfBloco({ id: 'rf_nc', status: 'nao_coberto' }),
        ],
        eventos: [
          createEvento({
            id: 'ev_done',
            data: HOJE,
            status: 'estudei',
            tempoAcumulado: 3600,
            discId: 'disc_1',
            rfBlocoId: 'rf_done',
            isAutoGenerated: true,
          }),
        ],
      })
    );

    expect(el.querySelector('[data-action="rf-quick-mark"]')).toBeNull();
    expect(el.querySelector('[data-action="rf-associar-historico"]')).toBeNull();
  });
});

describe('openAssociarHistorico — picker no #modal-prompt', () => {
  function mountModalPrompt() {
    document.body.innerHTML = `
      <div id="modal-prompt">
        <h3 id="modal-prompt-title"></h3>
        <div id="modal-prompt-body"></div>
        <button id="modal-prompt-save">Salvar</button>
        <button data-action="close-modal">Cancelar</button>
      </div>
    `;
  }

  it('lista candidatos da disciplina em ordem desc e abre o modal', async () => {
    store.setState(
      buildState({
        eventos: [
          createEvento({
            id: 'ev_antiga',
            titulo: 'Sessão antiga',
            data: '2026-07-01',
            dataEstudo: '2026-07-01',
            status: 'estudei',
            discId: 'disc_1',
          }),
          createEvento({
            id: 'ev_nova',
            titulo: 'Sessão nova',
            data: '2026-07-05',
            dataEstudo: '2026-07-05',
            status: 'estudei',
            discId: 'disc_1',
          }),
        ],
      })
    );
    logic.invalidateDiscCache();
    mountModalPrompt();
    const app = await import('../../src/js/app.js?v=8.37');
    const { openAssociarHistorico } = await import(
      '../../src/js/views/reta-final-associar.js?v=8.37'
    );

    const ok = openAssociarHistorico('rf_1');

    expect(ok).toBe(true);
    expect(app.openModal).toHaveBeenCalledWith('modal-prompt');
    const botoes = [...document.querySelectorAll('[data-associar-evento-id]')];
    expect(botoes.map((b) => b.dataset.associarEventoId)).toEqual(['ev_nova', 'ev_antiga']);
  });

  it('clicar num candidato associa a sessão e fecha o modal', async () => {
    store.setState(
      buildState({
        eventos: [
          createEvento({
            id: 'ev_manual',
            titulo: 'Sessão avulsa',
            data: '2026-07-05',
            dataEstudo: '2026-07-05',
            status: 'estudei',
            discId: 'disc_1',
          }),
        ],
      })
    );
    logic.invalidateDiscCache();
    mountModalPrompt();
    const app = await import('../../src/js/app.js?v=8.37');
    const { openAssociarHistorico } = await import(
      '../../src/js/views/reta-final-associar.js?v=8.37'
    );

    openAssociarHistorico('rf_1');
    document.querySelector('[data-associar-evento-id="ev_manual"]').click();

    const ev = store.state.eventos.find((e) => e.id === 'ev_manual');
    expect(ev.rfBlocoId).toBe('rf_1');
    expect(ev.dataEstudo).toBe('2026-07-05');
    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('concluido');
    expect(app.closeModal).toHaveBeenCalledWith('modal-prompt');
  });

  it('sem candidatos mostra empty-state', async () => {
    store.setState(buildState({ eventos: [] }));
    logic.invalidateDiscCache();
    mountModalPrompt();
    const { openAssociarHistorico } = await import(
      '../../src/js/views/reta-final-associar.js?v=8.37'
    );

    const ok = openAssociarHistorico('rf_1');

    expect(ok).toBe(true);
    expect(document.getElementById('modal-prompt-body').textContent).toContain(
      'Nenhuma sessão estudada desta disciplina disponível.'
    );
    expect(document.querySelectorAll('[data-associar-evento-id]')).toHaveLength(0);
  });

  it('restaura o rótulo do botão salvar ao fechar sem escolher', async () => {
    store.setState(buildState({ eventos: [] }));
    logic.invalidateDiscCache();
    mountModalPrompt();
    const { openAssociarHistorico } = await import(
      '../../src/js/views/reta-final-associar.js?v=8.37'
    );

    openAssociarHistorico('rf_1');
    const saveBtn = document.getElementById('modal-prompt-save');
    expect(saveBtn.textContent).not.toBe('Salvar');

    document.querySelector('[data-action="close-modal"]').click();
    expect(saveBtn.textContent).toBe('Salvar');
  });

  it('bloco inexistente retorna false sem abrir modal', async () => {
    store.setState(buildState());
    logic.invalidateDiscCache();
    mountModalPrompt();
    const app = await import('../../src/js/app.js?v=8.37');
    const { openAssociarHistorico } = await import(
      '../../src/js/views/reta-final-associar.js?v=8.37'
    );

    expect(openAssociarHistorico('rf_sumiu')).toBe(false);
    expect(app.openModal).not.toHaveBeenCalled();
  });
});
