import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createAssunto,
  createEdital,
} from '../helpers/state-builders.js';

// Espelho de cycle-sync-occupied-slots.test.js para a Reta Final: o agendador
// materializa eventos por bloco (rfBlocoId), nunca re-popula bloco ocupado por
// evento preservado e faz a rolagem "empilha no dia seguinte" no boot/render.

const HOJE = '2026-07-10';

let store;
let logic;
let retaFinalMod;

function rfBloco(overrides = {}) {
  return {
    id: 'rf_1',
    data: HOJE,
    dataOriginal: HOJE,
    discId: 'disc_1',
    topicos: [{ assId: 'ass_1', aulaId: null }],
    minutos: 90,
    status: 'pendente',
    rolagens: 0,
    ...overrides,
  };
}

function buildState({ eventos = [], blocos, planOverrides = {} } = {}) {
  return createBaseState({
    editais: [
      createEdital({
        id: 'ed_1',
        disciplinas: [
          createDisciplina({
            id: 'disc_1',
            nome: 'Direito Penal',
            assuntos: [createAssunto({ id: 'ass_1', nome: 'Crimes contra a vida' })],
          }),
          createDisciplina({ id: 'disc_2', nome: 'Português' }),
        ],
      }),
    ],
    planejamento: {
      ativo: true,
      tipo: 'reta_final',
      disciplinas: ['disc_1', 'disc_2'],
      relevancia: {},
      horarios: {},
      materiasPorDia: 3,
      sequencia: [],
      slotOverrides: [],
      ciclosCompletos: 0,
      dataInicioCicloAtual: '2026-07-07T00:00:00.000Z',
      updatedAt: '2026-07-07T10:00:00.000Z',
      retaFinal: {
        nome: 'Reta Final',
        dataFinal: '2026-08-15',
        minutosPadrao: 60,
        importadoEm: '2026-07-07T10:00:00.000Z',
        blocos: blocos || [rfBloco()],
      },
      ...planOverrides,
    },
    eventos,
  });
}

function eventosDoBloco(blocoId) {
  return store.state.eventos.filter((e) => e.rfBlocoId === blocoId);
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date(HOJE + 'T10:00:00'));

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  retaFinalMod = await import('../../src/js/logic/reta-final.js');
});

describe('syncRetaFinalToEventos — materialização e rolagem', () => {
  it('materializa evento autorf_ para bloco pendente de hoje/futuro', () => {
    store.setState(
      buildState({
        blocos: [
          rfBloco({ id: 'rf_hoje', data: HOJE }),
          rfBloco({ id: 'rf_fut', data: '2026-07-12', dataOriginal: '2026-07-12' }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    const evHoje = eventosDoBloco('rf_hoje');
    expect(evHoje).toHaveLength(1);
    expect(evHoje[0].id).toMatch(/^autorf_/);
    expect(evHoje[0].isAutoGenerated).toBe(true);
    expect(evHoje[0].data).toBe(HOJE);
    expect(evHoje[0].duracao).toBe(90);
    expect(evHoje[0].discId).toBe('disc_1');
    expect(evHoje[0].assId).toBe('ass_1');
    expect(eventosDoBloco('rf_fut')).toHaveLength(1);
  });

  it('syncCicloToEventos roteia plano reta_final para o agendador da reta final', () => {
    store.setState(buildState());
    logic.invalidateDiscCache();

    logic.syncCicloToEventos();

    expect(eventosDoBloco('rf_1')).toHaveLength(1);
  });

  it('é idempotente: segunda passada mantém os mesmos eventos', () => {
    store.setState(buildState());
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();
    const idsAntes = store.state.eventos.map((e) => e.id);
    retaFinalMod.syncRetaFinalToEventos();

    expect(store.state.eventos.map((e) => e.id)).toEqual(idsAntes);
  });

  it('bloco com sessão estudada vira concluido e não ganha novo evento', () => {
    store.setState(
      buildState({
        eventos: [
          createEvento({
            id: 'ev_estudado',
            data: HOJE,
            status: 'estudei',
            tempoAcumulado: 3600,
            discId: 'disc_1',
            rfBlocoId: 'rf_1',
            isAutoGenerated: true,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    const bloco = store.state.planejamento.retaFinal.blocos[0];
    expect(bloco.status).toBe('concluido');
    expect(eventosDoBloco('rf_1').map((e) => e.id)).toEqual(['ev_estudado']);
  });

  it('evento com timer parcial ocupa o bloco (nada novo por cima)', () => {
    store.setState(
      buildState({
        eventos: [
          createEvento({
            id: 'ev_parcial',
            data: HOJE,
            status: 'agendado',
            tempoAcumulado: 10 * 60,
            discId: 'disc_1',
            rfBlocoId: 'rf_1',
            isAutoGenerated: true,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    expect(eventosDoBloco('rf_1').map((e) => e.id)).toEqual(['ev_parcial']);
  });

  it('rolagem: bloco pendente de ontem sem evento preservado vai para hoje', () => {
    store.setState(
      buildState({
        blocos: [
          rfBloco({ id: 'rf_ontem', data: '2026-07-09', dataOriginal: '2026-07-09' }),
          rfBloco({ id: 'rf_hoje', data: HOJE }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    const blocos = store.state.planejamento.retaFinal.blocos;
    const rolado = blocos.find((b) => b.id === 'rf_ontem');
    expect(rolado.data).toBe(HOJE);
    expect(rolado.rolagens).toBe(1);
    // Ordenação estável: rolado entra depois do bloco que já era de hoje.
    expect(blocos.map((b) => b.id)).toEqual(['rf_hoje', 'rf_ontem']);
    expect(eventosDoBloco('rf_ontem')[0].data).toBe(HOJE);
  });

  it('rolagem NÃO altera planejamento.updatedAt (anti ping-pong LWW)', () => {
    store.setState(
      buildState({
        blocos: [rfBloco({ id: 'rf_ontem', data: '2026-07-09', dataOriginal: '2026-07-09' })],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    expect(store.state.planejamento.updatedAt).toBe('2026-07-07T10:00:00.000Z');
  });

  it('bloco atrasado com timer parcial NÃO rola (evento preservado)', () => {
    store.setState(
      buildState({
        blocos: [rfBloco({ id: 'rf_ontem', data: '2026-07-09', dataOriginal: '2026-07-09' })],
        eventos: [
          createEvento({
            id: 'ev_parcial',
            data: '2026-07-09',
            status: 'agendado',
            tempoAcumulado: 10 * 60,
            discId: 'disc_1',
            rfBlocoId: 'rf_ontem',
            isAutoGenerated: true,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    const bloco = store.state.planejamento.retaFinal.blocos[0];
    expect(bloco.data).toBe('2026-07-09');
    expect(bloco.rolagens).toBe(0);
  });

  it('pós-dataFinal: bloco atrasado vira nao_coberto e evento auto some', () => {
    vi.setSystemTime(new Date('2026-08-16T10:00:00'));
    store.setState(
      buildState({
        blocos: [rfBloco({ id: 'rf_a', data: '2026-08-14', dataOriginal: '2026-08-14' })],
        eventos: [
          createEvento({
            id: 'ev_auto',
            data: '2026-08-14',
            status: 'agendado',
            tempoAcumulado: 0,
            discId: 'disc_1',
            rfBlocoId: 'rf_a',
            isAutoGenerated: true,
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    expect(store.state.planejamento.retaFinal.blocos[0].status).toBe('nao_coberto');
    expect(eventosDoBloco('rf_a')).toHaveLength(0);
  });

  it('wipe: auto órfão (bloco em outra data) é removido; manual sobrevive', () => {
    store.setState(
      buildState({
        blocos: [rfBloco({ id: 'rf_1', data: '2026-07-12', dataOriginal: '2026-07-12' })],
        eventos: [
          createEvento({
            id: 'ev_orfao',
            data: HOJE,
            status: 'agendado',
            tempoAcumulado: 0,
            discId: 'disc_1',
            rfBlocoId: 'rf_1',
            isAutoGenerated: true,
          }),
          createEvento({
            id: 'ev_manual',
            data: HOJE,
            status: 'agendado',
            tempoAcumulado: 0,
            discId: 'disc_2',
          }),
        ],
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    expect(store.state.eventos.some((e) => e.id === 'ev_orfao')).toBe(false);
    expect(store.state.eventos.some((e) => e.id === 'ev_manual')).toBe(true);
    const novos = eventosDoBloco('rf_1');
    expect(novos).toHaveLength(1);
    expect(novos[0].data).toBe('2026-07-12');
  });

  it('plano de outro tipo é no-op', () => {
    store.setState(
      buildState({
        planOverrides: { tipo: 'ciclo', retaFinal: undefined },
      })
    );
    logic.invalidateDiscCache();

    retaFinalMod.syncRetaFinalToEventos();

    expect(store.state.eventos).toHaveLength(0);
  });
});

describe('getRetaFinalOccupiedBlocoIds', () => {
  it('retorna blocos com evento estudado ou com tempo acumulado', () => {
    const eventos = [
      { id: 'a', rfBlocoId: 'rf_1', status: 'estudei', tempoAcumulado: 3600 },
      { id: 'b', rfBlocoId: 'rf_2', status: 'agendado', tempoAcumulado: 60 },
      { id: 'c', rfBlocoId: 'rf_3', status: 'agendado', tempoAcumulado: 0 },
      { id: 'd', status: 'estudei', tempoAcumulado: 3600 },
    ];

    const occupied = retaFinalMod.getRetaFinalOccupiedBlocoIds(eventos);

    expect(occupied.has('rf_1')).toBe(true);
    expect(occupied.has('rf_2')).toBe(true);
    expect(occupied.has('rf_3')).toBe(false);
    expect(occupied.size).toBe(2);
  });
});
