import { beforeEach, describe, expect, it, vi } from 'vitest';
import { loadAppModules } from '../helpers/module-loader.js';
import {
  createBaseState,
  createEvento,
  createDisciplina,
  createEdital,
} from '../helpers/state-builders.js';

vi.mock('../../src/js/app.js?v=8.37', () => ({
  openModal: vi.fn(),
  closeModal: vi.fn(),
  showToast: vi.fn(),
  showConfirm: vi.fn(),
  navigate: vi.fn(),
  renderCurrentView: vi.fn(),
  updateBadges: vi.fn(),
  currentView: 'home',
}));

let store;
let logic;
let app;
let sessionSave;

function createMockDOM() {
  const elements = {};

  const createElement = (id) => {
    const el = {
      id,
      classList: { add: vi.fn(), remove: vi.fn(), toggle: vi.fn(), contains: vi.fn() },
      setAttribute: vi.fn(),
      textContent: '',
      innerHTML: '',
      children: [],
      value: '',
      style: { display: '' },
      dataset: {},
      addEventListener: vi.fn(),
      removeEventListener: vi.fn(),
      click: vi.fn(),
      focus: vi.fn(),
      blur: vi.fn(),
      remove: vi.fn(),
      contains: vi.fn(() => true),
      querySelectorAll: vi.fn(() => []),
      getBoundingClientRect: vi.fn(() => ({ top: 0, bottom: 0, left: 0, right: 0 })),
    };
    elements[id] = el;
    return el;
  };

  const mockDocument = {
    getElementById: vi.fn((id) => {
      if (!elements[id]) elements[id] = createElement(id);
      return elements[id];
    }),
    querySelector: vi.fn(() => null),
    querySelectorAll: vi.fn(() => []),
    dispatchEvent: vi.fn(),
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    activeElement: { blur: vi.fn() },
    body: { contains: vi.fn(() => true), style: {} },
    elements,
  };

  return mockDocument;
}

function setupCicloState({ evento = {}, discAName = 'Materia A' } = {}) {
  const discA = createDisciplina({ id: 'disc_a', nome: discAName });
  const discB = createDisciplina({ id: 'disc_b', nome: 'Materia B' });
  const edital = createEdital({ disciplinas: [discA, discB] });
  const evSlot = createEvento({
    id: 'ev_slot',
    titulo: 'Estudar Materia A',
    data: '2026-04-20',
    status: 'agendado',
    tempoAcumulado: 600,
    discId: 'disc_a',
    seqId: 'seq_a',
    slotIndex: 1,
    isAutoGenerated: true,
    ...evento,
  });
  store.setState(
    createBaseState({
      editais: [edital],
      eventos: [evSlot],
      planejamento: {
        ativo: true,
        tipo: 'ciclo',
        disciplinas: ['disc_a', 'disc_b'],
        relevancia: {},
        horarios: {},
        materiasPorDia: 3,
        sequencia: [
          { id: 'seq_a', discId: 'disc_a', minutosAlvo: 60, status: 'pendente', concluido: false },
          { id: 'seq_b', discId: 'disc_b', minutosAlvo: 60, status: 'pendente', concluido: false },
        ],
        skippedSlots: [],
        slotOverrides: [],
        ciclosCompletos: 0,
        dataInicioCicloAtual: '2026-04-01T00:00:00.000Z',
      },
    })
  );
  logic.invalidateDiscCache();
  return evSlot;
}

function saveArgs(extra = {}) {
  return {
    currentEventId: 'ev_slot',
    selectedTipos: ['teoria'],
    selectedMateriais: [],
    sessionStartTime: null,
    sessionEndTime: null,
    sessionMode: 'timer',
    ...extra,
  };
}

beforeEach(async () => {
  vi.resetModules();
  vi.useFakeTimers();
  vi.setSystemTime(new Date('2026-04-20T10:00:00Z'));

  const mockDoc = createMockDOM();
  global.document = mockDoc;
  global.window = {
    innerWidth: 1024,
    addEventListener: vi.fn(),
    removeEventListener: vi.fn(),
    navigate: vi.fn(),
    currentView: 'home',
  };
  global.Notification = { permission: 'granted' };
  global.Audio = vi.fn(() => ({ play: vi.fn(() => Promise.resolve()) }));
  global.localStorage = {
    getItem: vi.fn(() => null),
    setItem: vi.fn(),
    removeItem: vi.fn(),
    clear: vi.fn(),
  };
  global.sessionStorage = {
    getItem: vi.fn(() => null),
    setItem: vi.fn(),
    removeItem: vi.fn(),
    clear: vi.fn(),
  };

  const modules = await loadAppModules();
  store = modules.store;
  logic = modules.logic;
  app = await import('../../src/js/app.js?v=8.37');
  sessionSave = await import('../../src/js/registro-sessao/session-save.js?v=8.37');

  store.setState(createBaseState());
  logic.invalidateDiscCache();
  logic.invalidateRevCache();
  logic.invalidatePendingRevCache();
  logic.invalidateDashCaches();
  logic.invalidateStreakCache();
});

describe('registro-sessao/session-save.js — slots reais', () => {
  describe('substituição de slot (mode: substituir)', () => {
    it('desvincula o evento da etapa original para não concluí-la indevidamente', () => {
      setupCicloState();
      document.getElementById('reg-disciplina').value = 'disc_b';

      const result = sessionSave.performSave(
        saveArgs({ slotOverrideChoice: { mode: 'substituir', slotEventId: 'ev_slot' } })
      );

      expect(result).toBe(true);
      const ev = store.state.eventos.find((e) => e.id === 'ev_slot');
      expect(ev.status).toBe('estudei');
      expect(ev.discId).toBe('disc_b');
      // O evento substituto não representa mais o slot planejado: sem o
      // desvínculo, reconcilePlanningAfterSave oferece concluir a etapa
      // ORIGINAL (disc_a) com base numa sessão que virou disc_b.
      expect(ev.seqId).toBeUndefined();
      expect(ev.slotIndex).toBeUndefined();
      expect(app.showConfirm).not.toHaveBeenCalled();

      const override = store.state.planejamento.slotOverrides.find(
        (slot) => slot.data === '2026-04-20' && slot.slotIndex === 1
      );
      expect(override).toMatchObject({
        status: 'substituido',
        originalDiscId: 'disc_a',
        actualDiscId: 'disc_b',
        actualEventId: 'ev_slot',
      });
    });
  });

  describe('prompt de substituição', () => {
    it('não dispara ao editar sessão já estudada com disciplina trocada', () => {
      setupCicloState({
        evento: { status: 'estudei', data: '2026-04-18', dataEstudo: '2026-04-18', sessao: {} },
      });
      document.getElementById('reg-disciplina').value = 'disc_b';

      const result = sessionSave.performSave(saveArgs());

      expect(app.openModal).not.toHaveBeenCalledWith('modal-prompt');
      expect(result).toBe(true);
      expect(store.state.planejamento.slotOverrides).toEqual([]);
      const ev = store.state.eventos.find((e) => e.id === 'ev_slot');
      expect(ev.discId).toBe('disc_b');
    });

    it('escapa HTML no nome da disciplina exibido no prompt', () => {
      setupCicloState({ discAName: '<img src=x onerror=alert(1)> & "A"' });
      document.getElementById('reg-disciplina').value = 'disc_b';

      const result = sessionSave.performSave(saveArgs());

      expect(result).toBe(false);
      expect(app.openModal).toHaveBeenCalledWith('modal-prompt');
      const bodyEl = document.getElementById('modal-prompt-body');
      expect(bodyEl.innerHTML).not.toContain('<img src=x');
      expect(bodyEl.innerHTML).toContain('&lt;img');
    });

    it('salva como estudo extra se o modal-prompt não existir no DOM', () => {
      setupCicloState();
      document.getElementById('reg-disciplina').value = 'disc_b';
      const realGetElementById = document.getElementById;
      document.getElementById = vi.fn((id) =>
        id.startsWith('modal-prompt') ? null : realGetElementById(id)
      );

      const result = sessionSave.performSave(saveArgs());

      expect(result).toBe(true);
      const ev = store.state.eventos.find((e) => e.id === 'ev_slot');
      expect(ev.status).toBe('estudei');
      // extra: sem override registrado
      expect(store.state.planejamento.slotOverrides).toEqual([]);
    });

    it('restaura o rótulo do botão salvar quando o prompt é cancelado', () => {
      setupCicloState();
      document.getElementById('reg-disciplina').value = 'disc_b';
      const cancelListeners = [];
      const cancelBtn = {
        addEventListener: vi.fn((type, fn) => cancelListeners.push(fn)),
        removeEventListener: vi.fn(),
      };
      document.querySelectorAll = vi.fn((selector) =>
        selector.includes('close-modal') ? [cancelBtn] : []
      );

      sessionSave.performSave(saveArgs());

      const saveBtn = document.getElementById('modal-prompt-save');
      expect(saveBtn.textContent).toBe('Registrar como extra');
      cancelListeners.forEach((fn) => fn());
      expect(saveBtn.textContent).toBe('Salvar');
    });
  });
});
